import { existsSync } from "node:fs";
import { cp, mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

const PACKAGE_NAME = "agent-quality-police";
const MANAGED_BLOCK_START = "<!-- agent-quality-police:start -->";
const MANAGED_BLOCK_END = "<!-- agent-quality-police:end -->";

function timestamp() {
  return new Date().toISOString().replace(/[:.]/g, "-");
}

function homePath(homeDir, ...segments) {
  return path.join(homeDir, ...segments);
}

function packagePath(packageRoot, ...segments) {
  return path.join(packageRoot, ...segments);
}

function yamlScalar(value) {
  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }
  if (typeof value === "number") {
    return String(value);
  }
  const rendered = String(value);
  if (/^[A-Za-z0-9._/-]+$/.test(rendered)) {
    return rendered;
  }
  const escaped = rendered.replaceAll("\\", "\\\\").replaceAll('"', '\\"');
  return `"${escaped}"`;
}

function yamlLines(data) {
  const lines = ["---"];
  for (const [key, value] of Object.entries(data)) {
    if (Array.isArray(value)) {
      lines.push(`${key}:`);
      for (const item of value) {
        lines.push(`  - ${yamlScalar(item)}`);
      }
      continue;
    }
    if (value && typeof value === "object") {
      lines.push(`${key}:`);
      for (const [childKey, childValue] of Object.entries(value)) {
        if (childValue && typeof childValue === "object" && !Array.isArray(childValue)) {
          lines.push(`  ${childKey}:`);
          for (const [grandchildKey, grandchildValue] of Object.entries(childValue)) {
            lines.push(`    ${grandchildKey}: ${yamlScalar(grandchildValue)}`);
          }
          continue;
        }
        lines.push(`  ${childKey}: ${yamlScalar(childValue)}`);
      }
      continue;
    }
    lines.push(`${key}: ${yamlScalar(value)}`);
  }
  lines.push("---");
  return lines;
}

function tomlScalar(value) {
  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }
  if (typeof value === "number") {
    return String(value);
  }
  const escaped = String(value).replaceAll("\\", "\\\\").replaceAll('"', '\\"');
  return `"${escaped}"`;
}

function targetConfigRoot(target, homeDir) {
  if (target === "claude") {
    return homePath(homeDir, ".claude");
  }
  if (target === "codex") {
    return homePath(homeDir, ".codex");
  }
  if (target === "opencode") {
    return homePath(homeDir, ".config", "opencode");
  }
  throw new Error(`Unsupported target: ${target}`);
}

export function supportedTargets() {
  return ["claude", "codex", "opencode"];
}

async function loadEntrypointPolicy(packageRoot) {
  return (await readFile(packagePath(packageRoot, "framework", "entrypoints", "policy.md"), "utf8")).trimEnd();
}

async function loadAgentSpecs(packageRoot) {
  const specsRoot = packagePath(packageRoot, "framework", "agents", "specs");
  const promptRoot = packagePath(packageRoot, "framework", "agents", "prompts");
  const entries = (await readdir(specsRoot)).filter((entry) => entry.endsWith(".json")).sort();
  const specs = [];
  for (const entry of entries) {
    const spec = JSON.parse(await readFile(path.join(specsRoot, entry), "utf8"));
    if (typeof spec.promptPath === "string") {
      const promptPath = path.join(packageRoot, spec.promptPath);
      spec.prompt = (await readFile(promptPath, "utf8")).trimEnd();
    }
    specs.push(spec);
  }
  return specs;
}

function renderClaudeAgent(spec) {
  const frontmatter = {
    name: spec.name,
    description: spec.description,
  };
  for (const field of ["tools", "disallowedTools", "model", "permissionMode", "maxTurns", "skills"]) {
    if (field in spec.claude) {
      frontmatter[field] = spec.claude[field];
    }
  }
  return [...yamlLines(frontmatter), spec.prompt].join("\n");
}

function renderOpenCodeAgent(spec) {
  const frontmatter = {
    description: spec.description,
    mode: spec.opencode.mode,
  };
  for (const field of ["model", "temperature", "steps", "permission"]) {
    if (field in spec.opencode) {
      frontmatter[field] = spec.opencode[field];
    }
  }
  return ["# generated by framework/package/lib/install.mjs; do not edit directly", ...yamlLines(frontmatter), spec.prompt].join("\n");
}

function renderCodexAgent(spec) {
  const lines = [
    "# generated by framework/package/lib/install.mjs; do not edit directly",
    `name = ${tomlScalar(spec.name)}`,
    `description = ${tomlScalar(spec.description)}`,
  ];
  for (const field of ["model", "model_reasoning_effort", "sandbox_mode"]) {
    if (field in spec.codex) {
      lines.push(`${field} = ${tomlScalar(spec.codex[field])}`);
    }
  }
  const instructions = String(spec.prompt).replaceAll('"""', '\\"\\"\\"');
  lines.push('developer_instructions = """');
  lines.push(instructions);
  lines.push('"""');
  return lines.join("\n");
}

function renderTemplate(content, replacements) {
  let rendered = content;
  while (true) {
    let updated = rendered;
    for (const [key, value] of Object.entries(replacements)) {
      updated = updated.replaceAll(`{{${key}}}`, value);
    }
    if (updated === rendered) {
      return updated;
    }
    rendered = updated;
  }
}

function entrypointReplacements({
  qualityDefinitionPath,
  workflowPath,
  primarySkillRoot,
  skillRoot,
  systemLayoutPath,
  priorityBody,
  startupSequenceBody,
  skillRoutingBody,
  qualityRulesBody,
  reviewFlowBody
}) {
  return {
    quality_definition_path: qualityDefinitionPath,
    workflow_path: workflowPath,
    primary_skill_root: primarySkillRoot,
    quality_index_skill_path: `${skillRoot}/quality-index/SKILL.md`,
    grounding_first_skill_path: `${skillRoot}/grounding-first/SKILL.md`,
    typescript_zero_bypass_skill_path: `${skillRoot}/typescript-zero-bypass/SKILL.md`,
    vite_vitest_tdd_skill_path: `${skillRoot}/vite-vitest-tdd/SKILL.md`,
    react_public_api_testing_skill_path: `${skillRoot}/react-public-api-testing/SKILL.md`,
    anti_bypass_audit_skill_path: `${skillRoot}/anti-bypass-audit/SKILL.md`,
    refactoring_with_safety_skill_path: `${skillRoot}/refactoring-with-safety/SKILL.md`,
    governance_installation_skill_path: `${skillRoot}/governance-installation/SKILL.md`,
    system_layout_path: systemLayoutPath,
    priority_body: priorityBody,
    startup_sequence_body: startupSequenceBody,
    skill_routing_body: skillRoutingBody,
    quality_rules_body: qualityRulesBody,
    review_flow_body: reviewFlowBody
  };
}

function globalPolicySections() {
  return {
    priorityBody: [
      "- Instruções diretas de sistema, desenvolvedor e usuário sobrepõem este arquivo.",
      "- Prefira código local atual e documentação oficial atual sobre memória.",
      "- Dados de treinamento não são fonte de verdade; verifique cada afirmação não trivial com ferramenta ou cite a instrução literal do usuário.",
      "- Trate as skills e auditores exigidos neste arquivo como requisitos de workflow obrigatórios."
    ].join("\n"),
    startupSequenceBody: [
      "1. Confirme literalmente o pedido do usuário; se ambíguo, pergunte antes de começar.",
      "2. Leia [quality-definition]({{quality_definition_path}}) quando a tarefa precisar de contexto de política do repositório.",
      "3. Leia [workflow]({{workflow_path}}) quando o repositório definir um.",
      "4. Carregue o menor conjunto de skills exigido a partir de `{{primary_skill_root}}` antes de propor edits ou escrever código.",
      "5. Para mudanças de código, o agent principal coordena; a execução deve passar por `implementer`."
    ].join("\n"),
    skillRoutingBody: [
      "- Use [grounding-first]({{grounding_first_skill_path}}) sempre que a tarefa exigir afirmação factual sobre repositório, biblioteca ou intenção do usuário.",
      "- Use [quality-index]({{quality_index_skill_path}}) quando a tarefa cruza múltiplas áreas ou quando estiver em dúvida sobre quais validadores aplicar.",
      "- Use [typescript-zero-bypass]({{typescript_zero_bypass_skill_path}}) para mudanças em `.ts` ou `.tsx`.",
      "- Use [vite-vitest-tdd]({{vite_vitest_tdd_skill_path}}) para TDD em Vite ou Vitest.",
      "- Use [react-public-api-testing]({{react_public_api_testing_skill_path}}) para testes de comportamento em React.",
      "- Use [anti-bypass-audit]({{anti_bypass_audit_skill_path}}) ao revisar diffs, helpers suspeitos, configs enfraquecidas ou mudanças pesadas em tipagem/config.",
      "- Use [refactoring-with-safety]({{refactoring_with_safety_skill_path}}) para refactors que não são bug fix puro.",
      "- Use [governance-installation]({{governance_installation_skill_path}}) ao instalar ou atualizar este pacote de governança."
    ].join("\n"),
    qualityRulesBody: [
      "- Carregue as skills exigidas antes de propor edits ou escrever código.",
      "- Se uma skill exigida não estiver disponível no runtime atual, pare e reporte `BLOCKED`.",
      "- Use testes behavior-first quando testes forem viáveis.",
      "- Evite bypasses de tipo, bypasses por comentário, enfraquecimento de config e verdes falsos.",
      "- Use `?` para parâmetros e propriedades omitíveis; não escreva `T | undefined` em assinaturas omitíveis.",
      "- Contratos públicos devem manter uma forma estável de topo; não retorne uniões como `T[] | { data: T[]; total: number }`.",
      "- Arquivos de responsabilidade única são exigidos: uma classe por arquivo sem funções de topo irmãs, ou múltiplas funções exportadas apenas quando o nome do arquivo nomeia uma responsabilidade compartilhada.",
      "- Nomes genéricos como `helpers.ts`, `utils.ts`, `common.ts` ou `shared.ts` são falhas automáticas quando escondem a razão para mudar.",
      "- Quando houver mudança de código, a execução deve passar pelo `implementer`; edição direta pelo agent principal é bloqueio.",
      "- Não invente arquivos, APIs, imports, chaves de config ou comportamento de biblioteca; verifique com ferramenta primeiro.",
      "- Quando incerto, pare e pergunte ao usuário em vez de adivinhar.",
      "- Cite a fonte (`arquivo:linha`, URL oficial ou quote literal do usuário) para cada escolha não trivial de implementação.",
      "- Prefira tipos nomeados e modelos explícitos em vez de atalhos estruturais inline."
    ].join("\n"),
    reviewFlowBody: [
      "- Para mudanças de código, execute a implementação via `implementer`; o agent principal coordena, não substitui esse papel.",
      "- Para mudanças de código, invoque explicitamente os auditores exigidos antes da aprovação final.",
      "- Para mudanças de código, não finalize até que os auditores exigidos tenham rodado e seus resultados tenham sido revisados.",
      "- Não substitua invocação de agent de auditoria nominal por autorreview inline.",
      "- Antes de commit, push, merge request, release ou aprovação, valide os receipts exigidos em `.aqp/receipts/`.",
      "- Para tipagem, config, mocks, helpers ou diffs suspeitos, rode `bypass-auditor`.",
      "- Para mudanças de comportamento ou bug fixes, rode `tdd-warden` e `bypass-auditor`.",
      "- Para aprovação final, release ou decisão de merge, rode `pr-gatekeeper` após os demais auditores exigidos.",
      "- Se `implementer`, algum auditor exigido, ou a validação de receipts não puder rodar no runtime atual, pare e reporte `BLOCKED`."
    ].join("\n")
  };
}

function renderAgentsRoot(policy, replacements) {
  return `# AGENTS.md\n\n${renderTemplate(policy, replacements).trimEnd()}\n`;
}

function renderAgentsSnippet(policy, replacements) {
  return `${renderTemplate(policy, replacements).trimEnd()}\n`;
}

function renderClaudeRoot(policy, replacements) {
  return ["# CLAUDE.md", "", renderTemplate(policy, replacements).trimEnd(), ""].join("\n");
}

function renderClaudeSnippet(policy, replacements) {
  return `${renderTemplate(policy, replacements).trimEnd()}\n`;
}

function globalRootDestination(target, homeDir) {
  if (target === "claude") {
    return homePath(homeDir, ".claude", "CLAUDE.md");
  }
  if (target === "codex") {
    return homePath(homeDir, ".codex", "AGENTS.md");
  }
  if (target === "opencode") {
    return homePath(homeDir, ".config", "opencode", "AGENTS.md");
  }
  throw new Error(`Unsupported target: ${target}`);
}

function rootReplacements(target) {
  if (target === "claude") {
    return entrypointReplacements({
      qualityDefinitionPath: "docs/policy/quality-definition.md",
      workflowPath: "docs/policy/workflow.md",
      primarySkillRoot: "skills/",
      skillRoot: "skills",
      systemLayoutPath: "docs/policy/system-layout.md",
      ...globalPolicySections()
    });
  }
  if (target === "codex") {
    return entrypointReplacements({
      qualityDefinitionPath: "docs/policy/quality-definition.md",
      workflowPath: "docs/policy/workflow.md",
      primarySkillRoot: "../.agents/skills/",
      skillRoot: "../.agents/skills",
      systemLayoutPath: "docs/policy/system-layout.md",
      ...globalPolicySections()
    });
  }
  if (target === "opencode") {
    return entrypointReplacements({
      qualityDefinitionPath: "docs/policy/quality-definition.md",
      workflowPath: "docs/policy/workflow.md",
      primarySkillRoot: "skills/",
      skillRoot: "skills",
      systemLayoutPath: "docs/policy/system-layout.md",
      ...globalPolicySections()
    });
  }
  throw new Error(`Unsupported target: ${target}`);
}

async function renderRootFile(packageRoot, target) {
  const policy = await loadEntrypointPolicy(packageRoot);
  if (target === "claude") {
    return renderClaudeRoot(policy, rootReplacements(target));
  }
  return renderAgentsRoot(policy, rootReplacements(target));
}

async function renderRootSnippet(packageRoot, target) {
  const policy = await loadEntrypointPolicy(packageRoot);
  if (target === "claude") {
    return renderClaudeSnippet(policy, rootReplacements(target));
  }
  return renderAgentsSnippet(policy, rootReplacements(target));
}

export function resolveInstallPlan(packageRoot, target, homeDir = os.homedir()) {
  if (target === "claude") {
    return [
      [packagePath(packageRoot, "docs", "policy"), homePath(homeDir, ".claude", "docs", "policy")],
      [packagePath(packageRoot, "rules"), homePath(homeDir, ".claude", "rules")],
      [packagePath(packageRoot, "skills"), homePath(homeDir, ".claude", "skills")],
    ];
  }

  if (target === "codex") {
    return [
      [packagePath(packageRoot, "docs", "policy"), homePath(homeDir, ".codex", "docs", "policy")],
      [packagePath(packageRoot, "skills"), homePath(homeDir, ".agents", "skills")],
    ];
  }

  if (target === "opencode") {
    return [
      [packagePath(packageRoot, "docs", "policy"), homePath(homeDir, ".config", "opencode", "docs", "policy")],
      [packagePath(packageRoot, "skills"), homePath(homeDir, ".config", "opencode", "skills")],
    ];
  }

  throw new Error(`Unsupported target: ${target}`);
}

export function resolveCleanupPlan(target, homeDir = os.homedir(), manageGlobalRoot = false) {
  if (!manageGlobalRoot) {
    return [];
  }

  if (target === "claude") {
    return [homePath(homeDir, ".claude", "AGENTS.md")];
  }

  return [];
}

function normalizePlan(plan) {
  return plan
    .filter(([source, , optional]) => !optional || existsSync(source))
    .map(([source, destination]) => ({ source, destination }));
}

async function ensureParent(destination) {
  await mkdir(path.dirname(destination), { recursive: true });
}

function backupDestinationPath(destination, backupRoot, homeDir) {
  return path.join(backupRoot, path.relative(homeDir, destination));
}

async function backupExisting(destination, backupRoot, homeDir) {
  try {
    const backupDestination = backupDestinationPath(destination, backupRoot, homeDir);
    await ensureParent(backupDestination);
    await rename(destination, backupDestination);
    return true;
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      return false;
    }
    throw error;
  }
}

async function installEntry(source, destination) {
  await rm(destination, { recursive: true, force: true });
  await ensureParent(destination);
  await cp(source, destination, { recursive: true });
}

async function installRenderedAgents(packageRoot, target, destination) {
  const specs = await loadAgentSpecs(packageRoot);
  await rm(destination, { recursive: true, force: true });
  await mkdir(destination, { recursive: true });
  for (const spec of specs) {
    if (target === "claude") {
      await writeFile(path.join(destination, `${spec.name}.md`), `${renderClaudeAgent(spec).trimEnd()}\n`, "utf8");
      continue;
    }
    if (target === "codex") {
      await writeFile(path.join(destination, `${spec.name}.toml`), `${renderCodexAgent(spec).trimEnd()}\n`, "utf8");
      continue;
    }
    if (target === "opencode") {
      await writeFile(path.join(destination, `${spec.name}.md`), `${renderOpenCodeAgent(spec).trimEnd()}\n`, "utf8");
      continue;
    }
    throw new Error(`Unsupported target: ${target}`);
  }
}

async function writeRenderedEntry(content, destination) {
  await rm(destination, { recursive: true, force: true });
  await ensureParent(destination);
  await writeFile(destination, content, "utf8");
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function managedBlockPattern() {
  return new RegExp(
    `${escapeRegExp(MANAGED_BLOCK_START)}[\\s\\S]*?${escapeRegExp(MANAGED_BLOCK_END)}\\n?`,
    "m"
  );
}

function renderManagedBlock(content) {
  return [MANAGED_BLOCK_START, content.trimEnd(), MANAGED_BLOCK_END, ""].join("\n");
}

async function readOptionalText(destination) {
  try {
    return await readFile(destination, "utf8");
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      return null;
    }
    throw error;
  }
}

function mergeManagedRoot(existingContent, managedContent, legacyFullRoot) {
  const managedBlock = renderManagedBlock(managedContent);
  if (existingContent === null) {
    return managedBlock;
  }

  const existingTrimmed = existingContent.trim();
  if (existingTrimmed.length === 0) {
    return managedBlock;
  }

  const legacyTrimmed = legacyFullRoot.trim();
  if (existingTrimmed === legacyTrimmed) {
    return managedBlock;
  }

  const pattern = managedBlockPattern();
  if (pattern.test(existingContent)) {
    return existingContent.replace(pattern, managedBlock).trimEnd() + "\n";
  }

  return `${existingContent.trimEnd()}\n\n${managedBlock}`;
}

async function removeLegacyPath(destination, backupRoot, homeDir) {
  const backedUp = await backupExisting(destination, backupRoot, homeDir);
  if (!backedUp) {
    return false;
  }
  await rm(destination, { recursive: true, force: true });
  return true;
}

function renderManualStep(target, homeDir) {
  if (target === "claude") {
    return {
      target,
      kind: "append_to_claude_md",
      destination: homePath(homeDir, ".claude", "CLAUDE.md")
    };
  }

  if (target === "codex") {
    return {
      target,
      kind: "append_to_agents_md",
      destination: homePath(homeDir, ".codex", "AGENTS.md")
    };
  }

  if (target === "opencode") {
    return {
      target,
      kind: "append_to_agents_md",
      destination: homePath(homeDir, ".config", "opencode", "AGENTS.md")
    };
  }

  throw new Error(`Unsupported target: ${target}`);
}

export async function installGlobal(packageRoot, decisions, homeDir = os.homedir()) {
  const backupRoot = homePath(homeDir, `.${PACKAGE_NAME}`, "backups", timestamp());
  const installed = [];
  const manualSteps = [];

  for (const decision of decisions) {
    const { target, manageGlobalRoot } = decision;
    const cleanupPlan = resolveCleanupPlan(target, homeDir, manageGlobalRoot);
    for (const destination of cleanupPlan) {
      const removed = await removeLegacyPath(destination, backupRoot, homeDir);
      if (removed) {
        installed.push({
          target,
          source: null,
          destination,
          relativeDestination: path.relative(homeDir, destination),
          action: "remove"
        });
      }
    }

    const plan = normalizePlan(resolveInstallPlan(packageRoot, target, homeDir));
    for (const entry of plan) {
      const relativeDestination = path.relative(homeDir, entry.destination);
      await backupExisting(entry.destination, backupRoot, homeDir);
      await installEntry(entry.source, entry.destination);
      installed.push({
        target,
        source: entry.source,
        destination: entry.destination,
        relativeDestination,
        action: "install"
      });
    }

    const agentDestination = target === "claude"
      ? homePath(homeDir, ".claude", "agents")
      : target === "codex"
        ? homePath(homeDir, ".codex", "agents")
        : homePath(homeDir, ".config", "opencode", "agents");
    await backupExisting(agentDestination, backupRoot, homeDir);
    await installRenderedAgents(packageRoot, target, agentDestination);
    installed.push({
      target,
      source: `${target}:rendered-agents`,
      destination: agentDestination,
      relativeDestination: path.relative(homeDir, agentDestination),
      action: "install"
    });

    if (manageGlobalRoot) {
      const destination = globalRootDestination(target, homeDir);
      const existingContent = await readOptionalText(destination);
      const managedContent = await renderRootSnippet(packageRoot, target);
      const legacyFullRoot = await renderRootFile(packageRoot, target);
      const content = mergeManagedRoot(existingContent, managedContent, legacyFullRoot);
      await backupExisting(destination, backupRoot, homeDir);
      await writeRenderedEntry(content, destination);
      installed.push({
        target,
        source: `${target}:rendered-root`,
        destination,
        relativeDestination: path.relative(homeDir, destination),
        action: "write"
      });
      continue;
    }

    const manualStep = renderManualStep(target, homeDir);
    manualStep.snippet = await renderRootSnippet(packageRoot, target);
    manualSteps.push(manualStep);
  }

  return {
    backupRoot,
    installed,
    manualSteps
  };
}
