from __future__ import annotations

import argparse
import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any


GENERATED_MARKER = "<!-- generated by scripts/build_framework.py; do not edit directly -->"
PLACEHOLDER_PATTERN = re.compile(r"^\s*(TODO|TBD)([:\s]|$)", re.IGNORECASE)
LOCAL_LINK_PATTERN = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
AT_INCLUDE_PATTERN = re.compile(r"(?m)^@([A-Za-z0-9_./-]+)$")
ENTRYPOINT_TEMPLATE_PATTERN = re.compile(r"\{\{[a-z0-9_]+\}\}")


@dataclass(frozen=True)
class ValidationResult:
    errors: list[str]
    warnings: list[str]


class BuildError(RuntimeError):
    pass


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _load_entrypoint_policy(root: Path, *, required: bool) -> str | None:
    policy_path = root / "framework" / "entrypoints" / "policy.md"
    if not policy_path.exists():
        if required:
            raise BuildError(
                "Missing canonical entrypoint policy: framework/entrypoints/policy.md. "
                "Build requires canonical entrypoint sources before generated projections are reset."
            )
        return None
    return policy_path.read_text(encoding="utf-8").rstrip()


def _load_entrypoint_opencode_config(root: Path, *, required: bool) -> dict[str, Any] | None:
    config_path = root / "framework" / "entrypoints" / "opencode.json"
    if not config_path.exists():
        if required:
            raise BuildError(
                "Missing canonical OpenCode entrypoint config: framework/entrypoints/opencode.json. "
                "Build requires canonical entrypoint sources before generated projections are reset."
            )
        return None
    return _load_json(config_path)


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_normalized_output(content), encoding="utf-8")


def _normalized_output(content: str) -> str:
    return content.rstrip() + "\n"


def _reset_directory(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def _quote_yaml(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _yaml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    rendered = str(value)
    if re.fullmatch(r"[A-Za-z0-9._/-]+", rendered):
        return rendered
    return _quote_yaml(rendered)


def _yaml_lines(data: dict[str, Any]) -> list[str]:
    lines: list[str] = ["---"]
    for key, value in data.items():
        if isinstance(value, list):
            lines.append(f"{key}:")
            for item in value:
                lines.append(f"  - {_yaml_scalar(item)}")
        elif isinstance(value, dict):
            lines.append(f"{key}:")
            for child_key, child_value in value.items():
                if isinstance(child_value, dict):
                    lines.append(f"  {child_key}:")
                    for grandchild_key, grandchild_value in child_value.items():
                        lines.append(f"    {grandchild_key}: {_yaml_scalar(grandchild_value)}")
                else:
                    lines.append(f"  {child_key}: {_yaml_scalar(child_value)}")
        else:
            lines.append(f"{key}: {_yaml_scalar(value)}")
    lines.append("---")
    return lines


def _toml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _readable_name(path: Path) -> str:
    return str(path).replace(str(path.parent.parent.parent), "", 1)


def _load_skill_sources(root: Path, *, required: bool) -> list[Path]:
    source_root = root / ".claude" / "skills"
    if not source_root.exists():
        if required:
            raise BuildError(
                "Missing canonical skill source: .claude/skills. "
                "Build requires canonical sources before generated projections are reset."
            )
        return []

    source_skills = sorted(path for path in source_root.iterdir() if path.is_dir())
    if not source_skills and required:
        raise BuildError(
            "No canonical skill folders found under .claude/skills. "
            "Build requires canonical sources before generated projections are reset."
        )
    return source_skills


def build_skill_projection(root: Path, source_skills: list[Path] | None = None) -> list[str]:
    resolved_source_skills = source_skills if source_skills is not None else _load_skill_sources(root, required=True)
    destination_root = root / ".agents" / "skills"
    opencode_destination_root = root / ".opencode" / "skills"
    _reset_directory(destination_root)
    _reset_directory(opencode_destination_root)

    built_skills: list[str] = []
    for source_skill in resolved_source_skills:
        destination_skill = destination_root / source_skill.name
        opencode_destination_skill = opencode_destination_root / source_skill.name
        shutil.copytree(source_skill, destination_skill)
        shutil.copytree(source_skill, opencode_destination_skill)
        built_skills.append(source_skill.name)
    return built_skills


def _load_agent_specs(root: Path, *, required: bool) -> list[dict[str, Any]]:
    spec_root = root / "framework" / "agents" / "specs"
    if not spec_root.exists():
        if required:
            raise BuildError(
                "Missing canonical agent specs: framework/agents/specs. "
                "Build requires canonical agent sources before generated projections are reset."
            )
        return []
    spec_paths = sorted(spec_root.glob("*.json"))
    if not spec_paths:
        if required:
            raise BuildError(
                "No canonical agent spec files were found in framework/agents/specs. "
                "Build requires canonical agent sources before generated projections are reset."
            )
        return []
    specs: list[dict[str, Any]] = []
    for path in spec_paths:
        spec = _load_json(path)
        prompt_path = spec.get("promptPath")
        if prompt_path is not None:
            resolved_prompt = (root / prompt_path).read_text(encoding="utf-8").rstrip()
            spec["prompt"] = resolved_prompt
        specs.append(spec)
    return specs


def _render_claude_agent(spec: dict[str, Any]) -> str:
    claude = spec["claude"]
    frontmatter: dict[str, Any] = {
        "name": spec["name"],
        "description": spec["description"],
    }
    for field in ("tools", "disallowedTools", "model", "permissionMode", "maxTurns", "skills"):
        if field in claude:
            frontmatter[field] = claude[field]
    return "\n".join([*_yaml_lines(frontmatter), spec["prompt"]])


def _render_opencode_agent(spec: dict[str, Any]) -> str:
    opencode = spec["opencode"]
    frontmatter: dict[str, Any] = {
        "description": spec["description"],
        "mode": opencode["mode"],
    }
    for field in ("model", "temperature", "steps", "permission"):
        if field in opencode:
            frontmatter[field] = opencode[field]
    return "\n".join([GENERATED_MARKER, *_yaml_lines(frontmatter), spec["prompt"]])


def _render_codex_agent(spec: dict[str, Any]) -> str:
    codex = spec["codex"]
    lines = [
        f"# generated by scripts/build_framework.py; do not edit directly",
        f'name = "{spec["name"]}"',
        f'description = "{spec["description"]}"',
    ]
    for field in ("model", "model_reasoning_effort", "sandbox_mode"):
        if field in codex:
            lines.append(f'{field} = {_toml_scalar(codex[field])}')
    # Intentionally omit skills.config here. Codex already discovers repo skills from .agents/skills,
    # and the current official docs only demonstrate skills.config with absolute paths.
    instructions = spec["prompt"].replace('"""', '\\"\\"\\"')
    lines.append('developer_instructions = """')
    lines.append(instructions)
    lines.append('"""')
    return "\n".join(lines)


def build_agent_projections(root: Path, specs: list[dict[str, Any]] | None = None) -> list[str]:
    resolved_specs = specs if specs is not None else _load_agent_specs(root, required=True)
    built_agents: list[str] = []

    claude_root = root / ".claude" / "agents"
    opencode_root = root / ".opencode" / "agents"
    codex_root = root / ".codex" / "agents"
    _reset_directory(claude_root)
    _reset_directory(opencode_root)
    _reset_directory(codex_root)

    for spec in resolved_specs:
        name = spec["name"]
        _write_text(claude_root / f"{name}.md", _render_claude_agent(spec))
        _write_text(opencode_root / f"{name}.md", _render_opencode_agent(spec))
        _write_text(codex_root / f"{name}.toml", _render_codex_agent(spec))
        built_agents.append(name)
    return built_agents


def _load_distribution_spec(root: Path, *, required: bool) -> dict[str, Any] | None:
    spec_path = root / "framework" / "distribution" / "plugin.json"
    if not spec_path.exists():
        if required:
            raise BuildError(
                "Missing canonical distribution spec: framework/distribution/plugin.json. "
                "Build requires canonical package metadata before plugin distributions are reset."
            )
        return None
    return _load_json(spec_path)


def _copy_path(source: Path, destination: Path) -> None:
    if source.is_dir():
        shutil.copytree(source, destination)
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)


def _render_generated_package_json(distribution_spec: dict[str, Any]) -> str:
    package_manifest: dict[str, Any] = {
        "name": distribution_spec["name"],
        "version": distribution_spec["version"],
        "description": distribution_spec["description"],
        "type": "module",
        "license": distribution_spec["license"],
        "homepage": distribution_spec["homepage"],
        "repository": {
            "type": "git",
            "url": f'git+{distribution_spec["repository"]}',
        },
        "author": distribution_spec["author"],
        "keywords": distribution_spec["keywords"],
        "engines": {
            "node": ">=22.14.0",
        },
        "files": [
            "AGENTS.md",
            "CLAUDE.md",
            "opencode.json",
            "docs",
            ".claude",
            ".agents",
            ".codex",
            ".opencode",
            ".claude-plugin",
            ".codex-plugin",
            "framework",
            "bin",
            "lib",
            "README.md",
            "LICENSE",
        ],
        "bin": {
            "aqp": "bin/aqp.mjs",
        },
    }
    return json.dumps(package_manifest, indent=2) + "\n"


def _render_package_readme(distribution_spec: dict[str, Any]) -> str:
    package_name = distribution_spec["name"]
    return "\n".join(
        [
            f"# {package_name}",
            "",
            distribution_spec["description"],
            "",
            "## Install",
            "",
            f"```bash\nnpx {package_name} install\n```",
            "",
            "The installer asks which supported tools should be configured and whether it may manage each global root entrypoint.",
            "",
            "Supported tools:",
            "",
            "- Claude Code",
            "- Codex",
            "- OpenCode",
            "",
            "## Source",
            "",
            distribution_spec["homepage"],
            "",
        ]
    )


def _render_package_license(distribution_spec: dict[str, Any]) -> str:
    author_name = distribution_spec["author"]["name"]
    return "\n".join(
        [
            "MIT License",
            "",
            f"Copyright (c) {author_name}",
            "",
            "Permission is hereby granted, free of charge, to any person obtaining a copy",
            "of this software and associated documentation files (the \"Software\"), to deal",
            "in the Software without restriction, including without limitation the rights",
            "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell",
            "copies of the Software, and to permit persons to whom the Software is",
            "furnished to do so, subject to the following conditions:",
            "",
            "The above copyright notice and this permission notice shall be included in all",
            "copies or substantial portions of the Software.",
            "",
            "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR",
            "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,",
            "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE",
            "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER",
            "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,",
            "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE",
            "SOFTWARE.",
            "",
        ]
    )


def _render_publish_workflow(distribution_spec: dict[str, Any]) -> str:
    package_name = distribution_spec["name"]
    return "\n".join(
        [
            "name: Publish Package",
            "",
            "on:",
            "  workflow_dispatch:",
            "  push:",
            "    tags:",
            '      - "plugin-v*"',
            "",
            "jobs:",
            "  publish:",
            "    runs-on: ubuntu-latest",
            "    permissions:",
            "      contents: read",
            "      id-token: write",
            "    steps:",
            "      - name: Checkout",
            "        uses: actions/checkout@v6",
            "      - name: Setup Python",
            "        uses: actions/setup-python@v6",
            "        with:",
            '          python-version: "3.12"',
            "      - name: Setup Node",
            "        uses: actions/setup-node@v6",
            "        with:",
            '          node-version: "24"',
            '          registry-url: "https://registry.npmjs.org"',
            "      - name: Read package version",
            "        id: package",
            "        run: |",
            f"          VERSION=$(node -p \"require('./plugins/{package_name}/package.json').version\")",
            "          echo \"version=$VERSION\" >> \"$GITHUB_OUTPUT\"",
            "      - name: Read published version",
            "        id: published",
            f"        run: echo \"version=$(npm view {package_name} version 2>/dev/null || true)\" >> \"$GITHUB_OUTPUT\"",
            "      - name: Build framework",
            "        run: python3 scripts/build_framework.py",
            "      - name: Validate framework",
            "        run: python3 scripts/validate_framework.py",
            "      - name: Run Python tests",
            "        run: python3 -m unittest tests/test_framework_tools.py",
            "      - name: Run Node tests",
            "        run: node --test tests/node/install.test.mjs",
            "      - name: Publish package",
            "        if: steps.package.outputs.version != steps.published.outputs.version",
            f"        run: npm publish --access public\n        working-directory: plugins/{package_name}",
            "        env:",
            "          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}",
            "      - name: Skip publish when version already exists",
            "        if: steps.package.outputs.version == steps.published.outputs.version",
            "        run: echo \"Package version already published; skipping npm publish.\"",
            "",
        ]
    )


def _render_template(content: str, replacements: dict[str, str]) -> str:
    rendered = content
    while True:
        updated = rendered
        for key, value in replacements.items():
            updated = updated.replace(f"{{{{{key}}}}}", value)
        if updated == rendered:
            return updated
        rendered = updated


def _entrypoint_replacements(*, quality_definition_path: str, workflow_path: str, primary_skill_root: str, skill_root: str, system_layout_path: str, priority_body: str, startup_sequence_body: str, skill_routing_body: str, quality_rules_body: str, review_flow_body: str, tool_specific_notes: str) -> dict[str, str]:
    return {
        "quality_definition_path": quality_definition_path,
        "workflow_path": workflow_path,
        "primary_skill_root": primary_skill_root,
        "quality_index_skill_path": f"{skill_root}/quality-index/SKILL.md",
        "typescript_zero_bypass_skill_path": f"{skill_root}/typescript-zero-bypass/SKILL.md",
        "vite_vitest_tdd_skill_path": f"{skill_root}/vite-vitest-tdd/SKILL.md",
        "react_public_api_testing_skill_path": f"{skill_root}/react-public-api-testing/SKILL.md",
        "anti_bypass_audit_skill_path": f"{skill_root}/anti-bypass-audit/SKILL.md",
        "refactoring_with_safety_skill_path": f"{skill_root}/refactoring-with-safety/SKILL.md",
        "governance_installation_skill_path": f"{skill_root}/governance-installation/SKILL.md",
        "system_layout_path": system_layout_path,
        "priority_body": priority_body,
        "startup_sequence_body": startup_sequence_body,
        "skill_routing_body": skill_routing_body,
        "quality_rules_body": quality_rules_body,
        "review_flow_body": review_flow_body,
        "tool_specific_notes": tool_specific_notes,
    }


def _tool_notes_for(target: str, *, claude_entrypoint_label: str = "CLAUDE.md", claude_rules_root: str = ".claude/rules/", codex_skills_root: str = ".agents/skills/", codex_agents_root: str = ".codex/agents/", opencode_config_path: str = "opencode.json") -> str:
    if target == "claude":
        return f"- Claude Code should enter through `{claude_entrypoint_label}` and `{claude_rules_root}`."
    if target == "codex":
        return f"- Codex should enter through this file and use `{codex_skills_root}` plus `{codex_agents_root}`."
    if target == "opencode":
        return f"- OpenCode should enter through this file and load extra instructions from `{opencode_config_path}`."
    if target == "repo-agents":
        return "- AGENTS-aware tools should load only their local tool-specific skills and agents."
    return ""


def _repo_policy_sections() -> dict[str, str]:
    return {
        "priority_body": "\n".join(
            [
                "- Direct system, developer, and user instructions override this file.",
                "- [`docs/policy/quality-definition.md`]({{quality_definition_path}}) is the canonical definition of quality in this repository.",
                "- If any skill, rule, example, or agent prompt contradicts the quality definition, the quality definition wins.",
                "- Generated projections must not become the source of truth.",
            ]
        ),
        "startup_sequence_body": "\n".join(
            [
                "1. Read [quality-definition]({{quality_definition_path}}).",
                "2. Read [workflow]({{workflow_path}}).",
                "3. Load the smallest relevant skill set from `{{primary_skill_root}}`.",
                "4. Execute with TDD when tests are viable.",
                "5. Run the matching audit agents before final approval.",
            ]
        ),
        "skill_routing_body": "\n".join(
            [
                "- Use [quality-index]({{quality_index_skill_path}}) first when the task spans multiple concerns.",
                "- Use [typescript-zero-bypass]({{typescript_zero_bypass_skill_path}}) for any `.ts` or `.tsx` change.",
                "- Use [vite-vitest-tdd]({{vite_vitest_tdd_skill_path}}) when working with Vite, Vitest, or unit/component TDD.",
                "- Use [react-public-api-testing]({{react_public_api_testing_skill_path}}) for React component behavior tests.",
                "- Use [anti-bypass-audit]({{anti_bypass_audit_skill_path}}) when reviewing diffs, suspicious helpers, or weakened configs.",
                "- Use [refactoring-with-safety]({{refactoring_with_safety_skill_path}}) for refactors that are not pure bug fixes.",
                "- Use [governance-installation]({{governance_installation_skill_path}}) when installing or updating this framework in another repository.",
            ]
        ),
        "quality_rules_body": "\n".join(
            [
                "- TDD is mandatory when tests are technically viable.",
                "- A passing test suite without behavior proof is not a green build.",
                "- `any`, type assertions, non-null assertions, ts-comment bypasses, and lint/config weakening are automatic failures.",
                "- `Map` in public or domain-facing contracts is suspicious by default and must be treated as a modeling bypass unless a stronger repository rule explicitly allows it.",
                "- Helpers, factories, mocks, branches, or narrowing added only to silence the type system or to make tests easier are automatic failures.",
                "- Zod is allowed only at external input boundaries.",
                "- Joi is allowed only for environment validation when it is genuinely needed.",
                "- Strong named types are required.",
                "- Inline structural types are prohibited.",
                "- Reviewers must reject suspicious diffs instead of “accepting with caveats.”",
            ]
        ),
        "review_flow_body": "\n".join(
            [
                "- Fix the root problem, not the symptom.",
                "- Keep tests direct, short, and behavior-based.",
                "- Prefer explicit domain names over generic utilities.",
                "- Keep policy text severe and actionable; do not soften language to preserve agent comfort.",
                "- After any change to canonical framework sources such as `framework/skills/`, `framework/rules/`, `docs/policy/`, or `framework/agents/specs/`, run `python3 scripts/build_framework.py` before claiming the repository is consistent.",
                "- After the build step, run `python3 scripts/validate_framework.py`. If scripts changed, run `python3 -m unittest tests/test_framework_tools.py` and `node --test tests/node/install.test.mjs`.",
                "- Use `bypass-auditor` for typing, config, mocks, helpers, or suspicious diffs.",
                "- Use `tdd-warden` when behavior or tests changed or should have changed.",
                "- Use `pr-gatekeeper` only for final approve-or-reject review.",
            ]
        ),
    }


def _global_policy_sections() -> dict[str, str]:
    return {
        "priority_body": "\n".join(
            [
                "- Direct system, developer, and user instructions override this file.",
                "- Prefer current local code and current official documentation over memory.",
                "- Load only the smallest relevant skill set for the task.",
            ]
        ),
        "startup_sequence_body": "\n".join(
            [
                "1. Read [quality-definition]({{quality_definition_path}}) when the task needs repository policy context.",
                "2. Read [workflow]({{workflow_path}}) when the repository defines one.",
                "3. Load only the relevant skill set from `{{primary_skill_root}}`.",
            ]
        ),
        "skill_routing_body": "\n".join(
            [
                "- Use [quality-index]({{quality_index_skill_path}}) when the task spans multiple concerns.",
                "- Use [typescript-zero-bypass]({{typescript_zero_bypass_skill_path}}) for `.ts` or `.tsx` changes.",
                "- Use [vite-vitest-tdd]({{vite_vitest_tdd_skill_path}}) for Vite or Vitest TDD.",
                "- Use [react-public-api-testing]({{react_public_api_testing_skill_path}}) for React behavior tests.",
            ]
        ),
        "quality_rules_body": "\n".join(
            [
                "- Use behavior-first tests when tests are viable.",
                "- Avoid type bypasses, comment bypasses, config weakening, and fake greens.",
                "- Prefer named types and explicit models over inline structural shortcuts.",
            ]
        ),
        "review_flow_body": "\n".join(
            [
                "- Before final approval, run the relevant auditors for the actual risk surface.",
                "- Use `bypass-auditor` for typing, config, mocks, helpers, or suspicious diffs.",
                "- Use `tdd-warden` when behavior or tests changed or should have changed.",
                "- Use `pr-gatekeeper` only for final approve-or-reject review.",
            ]
        ),
    }


def _render_agents_md(entrypoint_policy: str, replacements: dict[str, str]) -> str:
    return "# AGENTS.md\n\n" + _render_template(entrypoint_policy, replacements).rstrip() + "\n"


def _render_repo_claude_md() -> str:
    return "\n".join(
        [
            "@AGENTS.md",
            "",
            "## Claude Code",
            "",
            "- Always-on rules live under `.claude/rules/`.",
            "- Skills live under `.claude/skills/`.",
            "- Claude subagents live under `.claude/agents/`.",
            "- If a skill and a rule both apply, the stricter instruction wins.",
            "- Use the repository workflow in `docs/policy/workflow.md` before finalizing any change.",
            "",
        ]
    )


def _render_packaged_claude_md(entrypoint_policy: str, replacements: dict[str, str]) -> str:
    rendered_policy = _render_template(entrypoint_policy, replacements)
    return "\n".join(
        [
            "# CLAUDE.md",
            "",
            rendered_policy.rstrip(),
            "",
            "## Claude Code",
            "",
            "- Always-on rules live under `.claude/rules/`.",
            "- Skills live under `.claude/skills/`.",
            "- Claude subagents live under `.claude/agents/`.",
            "- If a skill and a rule both apply, the stricter instruction wins.",
            "- Use the repository workflow in `docs/policy/workflow.md` before finalizing any change.",
            "",
        ]
    )


def _render_opencode_config(opencode_config: dict[str, Any]) -> str:
    return json.dumps(opencode_config, indent=2) + "\n"


def build_entrypoint_projections(root: Path, entrypoint_policy: str | None = None, opencode_config: dict[str, Any] | None = None) -> list[str]:
    resolved_entrypoint_policy = (
        entrypoint_policy if entrypoint_policy is not None else _load_entrypoint_policy(root, required=True)
    )
    resolved_opencode_config = (
        opencode_config if opencode_config is not None else _load_entrypoint_opencode_config(root, required=True)
    )
    assert resolved_entrypoint_policy is not None
    assert resolved_opencode_config is not None
    repo_replacements = _entrypoint_replacements(
        quality_definition_path="docs/policy/quality-definition.md",
        workflow_path="docs/policy/workflow.md",
        primary_skill_root=".claude/skills/",
        skill_root=".claude/skills",
        system_layout_path="docs/policy/system-layout.md",
        **_repo_policy_sections(),
        tool_specific_notes=_tool_notes_for("repo-agents"),
    )

    _write_text(root / "AGENTS.md", _render_agents_md(resolved_entrypoint_policy, repo_replacements))
    _write_text(root / "CLAUDE.md", _render_repo_claude_md())
    _write_text(root / "opencode.json", _render_opencode_config(resolved_opencode_config))
    return ["AGENTS.md", "CLAUDE.md", "opencode.json"]


def _render_claude_plugin_manifest(distribution_spec: dict[str, Any]) -> str:
    manifest = {
        "name": distribution_spec["name"],
        "version": distribution_spec["version"],
        "description": distribution_spec["description"],
        "author": distribution_spec["author"],
        "homepage": distribution_spec["homepage"],
        "repository": distribution_spec["repository"],
        "license": distribution_spec["license"],
        "keywords": distribution_spec["keywords"],
        "skills": "./.claude/skills",
        "agents": "./.claude/agents",
    }
    return json.dumps(manifest, indent=2) + "\n"


def _render_codex_plugin_manifest(distribution_spec: dict[str, Any]) -> str:
    manifest = {
        "name": distribution_spec["name"],
        "version": distribution_spec["version"],
        "description": distribution_spec["description"],
        "author": distribution_spec["author"],
        "homepage": distribution_spec["homepage"],
        "repository": distribution_spec["repository"],
        "license": distribution_spec["license"],
        "keywords": distribution_spec["keywords"],
        "skills": "./.agents/skills",
        "interface": distribution_spec["codexInterface"],
    }
    return json.dumps(manifest, indent=2) + "\n"


def _render_claude_marketplace(distribution_spec: dict[str, Any]) -> str:
    marketplace = distribution_spec["claudeMarketplace"]
    entry = {
        "name": distribution_spec["name"],
        "source": "./plugins/" + distribution_spec["name"],
        "description": distribution_spec["description"],
        "version": distribution_spec["version"],
        "author": distribution_spec["author"],
        "homepage": distribution_spec["homepage"],
        "repository": distribution_spec["repository"],
        "license": distribution_spec["license"],
        "keywords": distribution_spec["keywords"],
        "category": "Coding",
    }
    rendered = {
        "name": marketplace["name"],
        "owner": marketplace["owner"],
        "metadata": marketplace["metadata"],
        "plugins": [entry],
    }
    return json.dumps(rendered, indent=2) + "\n"


def _render_codex_marketplace(distribution_spec: dict[str, Any]) -> str:
    marketplace = distribution_spec["codexMarketplace"]
    entry = {
        "name": distribution_spec["name"],
        "source": {
            "source": "local",
            "path": "./plugins/" + distribution_spec["name"],
        },
        "policy": marketplace["policy"],
        "category": marketplace["category"],
    }
    rendered = {
        "name": marketplace["name"],
        "interface": marketplace["interface"],
        "plugins": [entry],
    }
    return json.dumps(rendered, indent=2) + "\n"


def build_plugin_distribution(root: Path, distribution_spec: dict[str, Any] | None = None) -> list[str]:
    resolved_distribution_spec = (
        distribution_spec if distribution_spec is not None else _load_distribution_spec(root, required=True)
    )
    assert resolved_distribution_spec is not None
    resolved_entrypoint_policy = _load_entrypoint_policy(root, required=True)
    resolved_opencode_config = _load_entrypoint_opencode_config(root, required=True)
    assert resolved_entrypoint_policy is not None
    assert resolved_opencode_config is not None

    plugin_root = root / "plugins" / resolved_distribution_spec["name"]
    _reset_directory(plugin_root)

    package_replacements = _entrypoint_replacements(
        quality_definition_path="docs/policy/quality-definition.md",
        workflow_path="docs/policy/workflow.md",
        primary_skill_root=".claude/skills/",
        skill_root=".claude/skills",
        system_layout_path="docs/policy/system-layout.md",
        **_global_policy_sections(),
        tool_specific_notes=_tool_notes_for("claude", claude_entrypoint_label="CLAUDE.md", claude_rules_root=".claude/rules/"),
    )

    copy_paths = [
        Path("AGENTS.md"),
        Path("opencode.json"),
        Path("docs") / "policy",
        Path(".claude") / "rules",
        Path(".claude") / "skills",
        Path(".claude") / "agents",
        Path(".agents") / "skills",
        Path(".codex") / "agents",
        Path(".opencode") / "skills",
        Path(".opencode") / "agents",
        Path("framework") / "entrypoints",
    ]
    for relative_path in copy_paths:
        source = root / relative_path
        if source.exists():
            _copy_path(source, plugin_root / relative_path)

    _copy_path(root / "framework" / "package" / "bin", plugin_root / "bin")
    _copy_path(root / "framework" / "package" / "lib", plugin_root / "lib")

    _write_text(plugin_root / "CLAUDE.md", _render_packaged_claude_md(resolved_entrypoint_policy, package_replacements))
    _write_text(plugin_root / "README.md", _render_package_readme(resolved_distribution_spec))
    _write_text(plugin_root / "LICENSE", _render_package_license(resolved_distribution_spec))
    _write_text(plugin_root / "package.json", _render_generated_package_json(resolved_distribution_spec))
    _write_text(
        plugin_root / ".claude-plugin" / "plugin.json",
        _render_claude_plugin_manifest(resolved_distribution_spec),
    )
    _write_text(
        plugin_root / ".codex-plugin" / "plugin.json",
        _render_codex_plugin_manifest(resolved_distribution_spec),
    )
    _write_text(root / ".github" / "workflows" / "publish-package.yml", _render_publish_workflow(resolved_distribution_spec))
    _write_text(root / ".claude-plugin" / "marketplace.json", _render_claude_marketplace(resolved_distribution_spec))
    _write_text(root / ".agents" / "plugins" / "marketplace.json", _render_codex_marketplace(resolved_distribution_spec))

    return [resolved_distribution_spec["name"]]


def _iter_text_files(root: Path) -> list[Path]:
    text_paths: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if ".git" in path.parts:
            continue
        if path.suffix in {".md", ".json", ".py", ".toml", ".txt", ".ts", ".tsx"} or path.name == "SKILL.md":
            text_paths.append(path)
    return sorted(text_paths)


def _relative_file_set(root: Path) -> set[Path]:
    files: set[Path] = set()
    for path in root.rglob("*"):
        if path.is_file():
            files.add(path.relative_to(root))
    return files


def _expected_agent_projections(root: Path) -> dict[Path, str]:
    expected: dict[Path, str] = {}
    for spec in _load_agent_specs(root, required=False):
        name = spec["name"]
        expected[Path(".claude") / "agents" / f"{name}.md"] = _normalized_output(_render_claude_agent(spec))
        expected[Path(".opencode") / "agents" / f"{name}.md"] = _normalized_output(_render_opencode_agent(spec))
        expected[Path(".codex") / "agents" / f"{name}.toml"] = _normalized_output(_render_codex_agent(spec))
    return expected


def _expected_entrypoint_projections(root: Path) -> dict[Path, str]:
    entrypoint_policy = _load_entrypoint_policy(root, required=False)
    opencode_config = _load_entrypoint_opencode_config(root, required=False)
    if entrypoint_policy is None or opencode_config is None:
        return {}
    repo_replacements = _entrypoint_replacements(
        quality_definition_path="docs/policy/quality-definition.md",
        workflow_path="docs/policy/workflow.md",
        primary_skill_root=".claude/skills/",
        skill_root=".claude/skills",
        system_layout_path="docs/policy/system-layout.md",
        **_repo_policy_sections(),
        tool_specific_notes=_tool_notes_for("repo-agents"),
    )
    return {
        Path("AGENTS.md"): _normalized_output(_render_agents_md(entrypoint_policy, repo_replacements)),
        Path("CLAUDE.md"): _normalized_output(_render_repo_claude_md()),
        Path("opencode.json"): _normalized_output(_render_opencode_config(opencode_config)),
    }


def _expected_plugin_distribution(root: Path) -> dict[Path, str]:
    distribution_spec = _load_distribution_spec(root, required=False)
    entrypoint_policy = _load_entrypoint_policy(root, required=False)
    opencode_config = _load_entrypoint_opencode_config(root, required=False)
    if distribution_spec is None or entrypoint_policy is None or opencode_config is None:
        return {}

    expected: dict[Path, str] = {}
    plugin_root = Path("plugins") / distribution_spec["name"]
    package_replacements = _entrypoint_replacements(
        quality_definition_path="docs/policy/quality-definition.md",
        workflow_path="docs/policy/workflow.md",
        primary_skill_root=".claude/skills/",
        skill_root=".claude/skills",
        system_layout_path="docs/policy/system-layout.md",
        **_global_policy_sections(),
        tool_specific_notes=_tool_notes_for("claude", claude_entrypoint_label="CLAUDE.md", claude_rules_root=".claude/rules/"),
    )
    expected[plugin_root / "package.json"] = _normalized_output(_render_generated_package_json(distribution_spec))
    expected[plugin_root / "README.md"] = _normalized_output(_render_package_readme(distribution_spec))
    expected[plugin_root / "LICENSE"] = _normalized_output(_render_package_license(distribution_spec))
    expected[plugin_root / ".claude-plugin" / "plugin.json"] = _normalized_output(
        _render_claude_plugin_manifest(distribution_spec)
    )
    expected[plugin_root / ".codex-plugin" / "plugin.json"] = _normalized_output(
        _render_codex_plugin_manifest(distribution_spec)
    )
    expected[Path(".claude-plugin") / "marketplace.json"] = _normalized_output(
        _render_claude_marketplace(distribution_spec)
    )
    expected[Path(".github") / "workflows" / "publish-package.yml"] = _normalized_output(
        _render_publish_workflow(distribution_spec)
    )
    expected[Path(".agents") / "plugins" / "marketplace.json"] = _normalized_output(
        _render_codex_marketplace(distribution_spec)
    )

    copied_roots = [
        Path("AGENTS.md"),
        Path("opencode.json"),
        Path("docs") / "policy",
        Path(".claude") / "rules",
        Path(".claude") / "skills",
        Path(".claude") / "agents",
        Path(".agents") / "skills",
        Path(".codex") / "agents",
        Path(".opencode") / "skills",
        Path(".opencode") / "agents",
        Path("framework") / "entrypoints",
    ]
    expected[plugin_root / "CLAUDE.md"] = _normalized_output(
        _render_packaged_claude_md(entrypoint_policy, package_replacements)
    )
    for relative_root in copied_roots:
        source = root / relative_root
        if source.is_file():
            expected[plugin_root / relative_root] = _normalized_output(source.read_text(encoding="utf-8"))
            continue
        if not source.exists():
            continue
        for path in source.rglob("*"):
            if not path.is_file():
                continue
            expected[plugin_root / path.relative_to(root)] = _normalized_output(path.read_text(encoding="utf-8"))

    package_source_roots = [
        (root / "framework" / "package" / "bin", plugin_root / "bin"),
        (root / "framework" / "package" / "lib", plugin_root / "lib"),
    ]
    for source_root, destination_root in package_source_roots:
        if not source_root.exists():
            continue
        for path in source_root.rglob("*"):
            if not path.is_file():
                continue
            expected[destination_root / path.relative_to(source_root)] = _normalized_output(
                path.read_text(encoding="utf-8")
            )

    return expected


def _check_local_links(root: Path, path: Path, content: str) -> list[str]:
    errors: list[str] = []
    for _, target in LOCAL_LINK_PATTERN.findall(content):
        if target.startswith(("http://", "https://", "mailto:", "#")):
            continue
        normalized_target = target.split("#", 1)[0]
        candidate = (path.parent / normalized_target).resolve()
        if not candidate.exists():
            errors.append(f"Broken link in {path.relative_to(root)} -> {target}")
    for include_target in AT_INCLUDE_PATTERN.findall(content):
        candidate = (path.parent / include_target).resolve()
        if not candidate.exists():
            errors.append(f"Broken include in {path.relative_to(root)} -> @{include_target}")
    return errors


def _is_entrypoint_template(path: Path, content: str) -> bool:
    return "framework" in path.parts and "entrypoints" in path.parts and bool(ENTRYPOINT_TEMPLATE_PATTERN.search(content))


def validate_repository(root: Path) -> ValidationResult:
    errors: list[str] = []
    warnings: list[str] = []

    required_files = [
        root / "README.md",
        root / "AGENTS.md",
        root / "CLAUDE.md",
        root / "docs" / "policy" / "quality-definition.md",
    ]
    for path in required_files:
        if not path.exists():
            errors.append(f"Missing required file: {path.relative_to(root)}")

    for path in _iter_text_files(root):
        content = path.read_text(encoding="utf-8")
        if PLACEHOLDER_PATTERN.search(content):
            errors.append(f"Placeholder token found in {path.relative_to(root)}")
        if path.suffix in {".md", ".json", ".toml"} and (
            "REPO_NAME=" in content or "REPO_DESCRIPTION=" in content
        ):
            errors.append(f"Unresolved repository placeholder found in {path.relative_to(root)}")
        if (path.suffix == ".md" or path.name == "SKILL.md") and not _is_entrypoint_template(path, content):
            errors.extend(_check_local_links(root, path, content))

    claude_skills_root = root / ".claude" / "skills"
    agents_skills_root = root / ".agents" / "skills"
    opencode_skills_root = root / ".opencode" / "skills"
    if claude_skills_root.exists():
        claude_skill_names = sorted(path.name for path in claude_skills_root.iterdir() if path.is_dir())
        agents_skill_names = (
            sorted(path.name for path in agents_skills_root.iterdir() if path.is_dir())
            if agents_skills_root.exists()
            else []
        )
        opencode_skill_names = (
            sorted(path.name for path in opencode_skills_root.iterdir() if path.is_dir())
            if opencode_skills_root.exists()
            else []
        )
        if claude_skill_names != agents_skill_names:
            errors.append("Skill projection mismatch between .claude/skills and .agents/skills")
        if claude_skill_names != opencode_skill_names:
            errors.append("Skill projection mismatch between .claude/skills and .opencode/skills")

        claude_skill_files = _relative_file_set(claude_skills_root)
        if agents_skills_root.exists():
            agents_skill_files = _relative_file_set(agents_skills_root)
            if claude_skill_files != agents_skill_files:
                errors.append("Skill projection file set mismatch between .claude/skills and .agents/skills")
            else:
                for relative_path in sorted(claude_skill_files):
                    claude_content = (claude_skills_root / relative_path).read_text(encoding="utf-8")
                    agents_content = (agents_skills_root / relative_path).read_text(encoding="utf-8")
                    if claude_content != agents_content:
                        errors.append(
                            "Skill projection content drift between "
                            f".claude/skills/{relative_path} and .agents/skills/{relative_path}"
                        )
        if opencode_skills_root.exists():
            opencode_skill_files = _relative_file_set(opencode_skills_root)
            if claude_skill_files != opencode_skill_files:
                errors.append("Skill projection file set mismatch between .claude/skills and .opencode/skills")
            else:
                for relative_path in sorted(claude_skill_files):
                    claude_content = (claude_skills_root / relative_path).read_text(encoding="utf-8")
                    opencode_content = (opencode_skills_root / relative_path).read_text(encoding="utf-8")
                    if claude_content != opencode_content:
                        errors.append(
                            "Skill projection content drift between "
                            f".claude/skills/{relative_path} and .opencode/skills/{relative_path}"
                        )

    expected_entrypoint_projections = _expected_entrypoint_projections(root)
    for relative_path, expected_content in expected_entrypoint_projections.items():
        actual_path = root / relative_path
        if not actual_path.exists():
            errors.append(f"Missing generated entrypoint file: {relative_path}")
            continue
        actual_content = actual_path.read_text(encoding="utf-8")
        if actual_content != expected_content:
            errors.append(
                "Generated entrypoint drift between canonical entrypoint sources and "
                f"{relative_path}"
            )

    expected_agent_projections = _expected_agent_projections(root)
    if expected_agent_projections:
        expected_paths = set(expected_agent_projections.keys())
        actual_paths: set[Path] = set()
        for agent_root in (root / ".claude" / "agents", root / ".opencode" / "agents", root / ".codex" / "agents"):
            if not agent_root.exists():
                continue
            actual_paths.update(
                path.relative_to(root)
                for path in agent_root.iterdir()
                if path.is_file()
            )

        if actual_paths != expected_paths:
            errors.append(
                "Generated agent file set drift between framework/agents/specs and generated agent projections"
            )

        for relative_path, expected_content in expected_agent_projections.items():
            actual_path = root / relative_path
            if not actual_path.exists():
                errors.append(f"Missing generated agent file: {relative_path}")
                continue
            actual_content = actual_path.read_text(encoding="utf-8")
            if actual_content != expected_content:
                errors.append(
                    "Generated agent content drift between canonical specs/prompts and "
                    f"{relative_path}"
                )

    expected_plugin_distribution = _expected_plugin_distribution(root)
    for relative_path, expected_content in expected_plugin_distribution.items():
        actual_path = root / relative_path
        if not actual_path.exists():
            errors.append(f"Missing generated plugin distribution file: {relative_path}")
            continue
        actual_content = actual_path.read_text(encoding="utf-8")
        if actual_content != expected_content:
            errors.append(
                "Generated plugin distribution drift between canonical sources and "
                f"{relative_path}"
            )

    return ValidationResult(errors=errors, warnings=warnings)


def build_all(root: Path) -> tuple[list[str], list[str], list[str], list[str]]:
    entrypoint_policy = _load_entrypoint_policy(root, required=True)
    assert entrypoint_policy is not None
    source_skills = _load_skill_sources(root, required=True)
    specs = _load_agent_specs(root, required=True)
    distribution_spec = _load_distribution_spec(root, required=True)
    entrypoints = build_entrypoint_projections(root, entrypoint_policy)
    skills = build_skill_projection(root, source_skills)
    agents = build_agent_projections(root, specs)
    distributions = build_plugin_distribution(root, distribution_spec)
    return entrypoints, skills, agents, distributions


def _default_root() -> Path:
    return Path(__file__).resolve().parent.parent


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build or validate the agent governance framework.")
    parser.add_argument("command", choices=("build", "validate"))
    parser.add_argument("--root", default=str(_default_root()))
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    if args.command == "build":
        try:
            entrypoints, skills, agents, distributions = build_all(root)
        except BuildError as error:
            print(f"ERROR: {error}")
            return 1
        print(
            " ".join(
                [
                    f"built-entrypoints={len(entrypoints)}",
                    f"built-skills={len(skills)}",
                    f"built-agents={len(agents)}",
                    f"built-distributions={len(distributions)}",
                ]
            )
        )
        return 0

    result = validate_repository(root)
    for warning in result.warnings:
        print(f"WARNING: {warning}")
    for error in result.errors:
        print(f"ERROR: {error}")
    if result.errors:
        return 1
    print("validation-ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
