from __future__ import annotations

import argparse
import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any


GENERATED_MARKER = "<!-- generated by scripts/build_framework.py; do not edit directly -->"
PLACEHOLDER_PATTERN = re.compile(r"^\s*(TODO|TBD)([:\s]|$)", re.IGNORECASE)
LOCAL_LINK_PATTERN = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
AT_INCLUDE_PATTERN = re.compile(r"(?m)^@([A-Za-z0-9_./-]+)$")
ENTRYPOINT_TEMPLATE_PATTERN = re.compile(r"\{\{[a-z0-9_]+\}\}")


@dataclass(frozen=True)
class ValidationResult:
    errors: list[str]
    warnings: list[str]


class BuildError(RuntimeError):
    pass


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _load_entrypoint_policy(root: Path, *, required: bool) -> str | None:
    policy_path = root / "framework" / "entrypoints" / "policy.md"
    if not policy_path.exists():
        if required:
            raise BuildError(
                "Missing canonical entrypoint policy: framework/entrypoints/policy.md. "
                "Build requires canonical entrypoint sources before generated projections are reset."
            )
        return None
    return policy_path.read_text(encoding="utf-8").rstrip()


def _load_entrypoint_opencode_config(root: Path, *, required: bool) -> dict[str, Any] | None:
    config_path = root / "framework" / "entrypoints" / "opencode.json"
    if not config_path.exists():
        if required:
            raise BuildError(
                "Missing canonical OpenCode entrypoint config: framework/entrypoints/opencode.json. "
                "Build requires canonical entrypoint sources before generated projections are reset."
            )
        return None
    return _load_json(config_path)


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_normalized_output(content), encoding="utf-8")


def _normalized_output(content: str) -> str:
    return content.rstrip() + "\n"


def _reset_directory(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def _quote_yaml(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _yaml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    rendered = str(value)
    if re.fullmatch(r"[A-Za-z0-9._/-]+", rendered):
        return rendered
    return _quote_yaml(rendered)


def _yaml_lines(data: dict[str, Any]) -> list[str]:
    lines: list[str] = ["---"]
    for key, value in data.items():
        if isinstance(value, list):
            lines.append(f"{key}:")
            for item in value:
                lines.append(f"  - {_yaml_scalar(item)}")
        elif isinstance(value, dict):
            lines.append(f"{key}:")
            for child_key, child_value in value.items():
                if isinstance(child_value, dict):
                    lines.append(f"  {child_key}:")
                    for grandchild_key, grandchild_value in child_value.items():
                        lines.append(f"    {grandchild_key}: {_yaml_scalar(grandchild_value)}")
                else:
                    lines.append(f"  {child_key}: {_yaml_scalar(child_value)}")
        else:
            lines.append(f"{key}: {_yaml_scalar(value)}")
    lines.append("---")
    return lines


def _toml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _readable_name(path: Path) -> str:
    return str(path).replace(str(path.parent.parent.parent), "", 1)


def _load_skill_sources(root: Path, *, required: bool) -> list[Path]:
    source_root = root / "framework" / "skills"
    if not source_root.exists():
        if required:
            raise BuildError(
                "Missing canonical skill source: framework/skills. "
                "Build requires canonical sources before generated projections are reset."
            )
        return []

    source_skills = sorted(path for path in source_root.iterdir() if path.is_dir())
    if not source_skills and required:
        raise BuildError(
            "No canonical skill folders found under framework/skills. "
            "Build requires canonical sources before generated projections are reset."
        )
    return source_skills


def build_skill_projection(root: Path, source_skills: list[Path] | None = None) -> list[str]:
    resolved_source_skills = source_skills if source_skills is not None else _load_skill_sources(root, required=True)
    built_skills: list[str] = []
    for source_skill in resolved_source_skills:
        built_skills.append(source_skill.name)
    return built_skills


def _load_agent_specs(root: Path, *, required: bool) -> list[dict[str, Any]]:
    spec_root = root / "framework" / "agents" / "specs"
    if not spec_root.exists():
        if required:
            raise BuildError(
                "Missing canonical agent specs: framework/agents/specs. "
                "Build requires canonical agent sources before generated projections are reset."
            )
        return []
    spec_paths = sorted(spec_root.glob("*.json"))
    if not spec_paths:
        if required:
            raise BuildError(
                "No canonical agent spec files were found in framework/agents/specs. "
                "Build requires canonical agent sources before generated projections are reset."
            )
        return []
    specs: list[dict[str, Any]] = []
    for path in spec_paths:
        spec = _load_json(path)
        prompt_path = spec.get("promptPath")
        if prompt_path is not None:
            resolved_prompt = (root / prompt_path).read_text(encoding="utf-8").rstrip()
            spec["prompt"] = resolved_prompt
        specs.append(spec)
    return specs


def _render_claude_agent(spec: dict[str, Any]) -> str:
    claude = spec["claude"]
    frontmatter: dict[str, Any] = {
        "name": spec["name"],
        "description": spec["description"],
    }
    for field in ("tools", "disallowedTools", "model", "permissionMode", "maxTurns", "skills"):
        if field in claude:
            frontmatter[field] = claude[field]
    return "\n".join([*_yaml_lines(frontmatter), spec["prompt"]])


def _render_opencode_agent(spec: dict[str, Any]) -> str:
    opencode = spec["opencode"]
    frontmatter: dict[str, Any] = {
        "description": spec["description"],
        "mode": opencode["mode"],
    }
    for field in ("model", "temperature", "steps", "permission"):
        if field in opencode:
            frontmatter[field] = opencode[field]
    return "\n".join([GENERATED_MARKER, *_yaml_lines(frontmatter), spec["prompt"]])


def _render_codex_agent(spec: dict[str, Any]) -> str:
    codex = spec["codex"]
    lines = [
        f"# generated by scripts/build_framework.py; do not edit directly",
        f'name = "{spec["name"]}"',
        f'description = "{spec["description"]}"',
    ]
    for field in ("model", "model_reasoning_effort", "sandbox_mode"):
        if field in codex:
            lines.append(f'{field} = {_toml_scalar(codex[field])}')
    # Intentionally omit skills.config here. Codex already discovers repo skills from .agents/skills,
    # and the current official docs only demonstrate skills.config with absolute paths.
    instructions = spec["prompt"].replace('"""', '\\"\\"\\"')
    lines.append('developer_instructions = """')
    lines.append(instructions)
    lines.append('"""')
    return "\n".join(lines)


def build_agent_projections(root: Path, specs: list[dict[str, Any]] | None = None) -> list[str]:
    resolved_specs = specs if specs is not None else _load_agent_specs(root, required=True)
    built_agents: list[str] = []

    for spec in resolved_specs:
        built_agents.append(spec["name"])
    return built_agents


def _load_distribution_spec(root: Path, *, required: bool) -> dict[str, Any] | None:
    spec_path = root / "framework" / "distribution" / "plugin.json"
    if not spec_path.exists():
        if required:
            raise BuildError(
                "Missing canonical distribution spec: framework/distribution/plugin.json. "
                "Build requires canonical package metadata before plugin distributions are reset."
            )
        return None
    return _load_json(spec_path)


def _copy_path(source: Path, destination: Path) -> None:
    if source.is_dir():
        shutil.copytree(source, destination)
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)


def _render_generated_package_json(distribution_spec: dict[str, Any]) -> str:
    package_manifest: dict[str, Any] = {
        "name": distribution_spec["name"],
        "version": distribution_spec["version"],
        "description": distribution_spec["description"],
        "type": "module",
        "license": distribution_spec["license"],
        "homepage": distribution_spec["homepage"],
        "repository": {
            "type": "git",
            "url": f'git+{distribution_spec["repository"]}',
        },
        "author": distribution_spec["author"],
        "keywords": distribution_spec["keywords"],
        "engines": {
            "node": ">=22.14.0",
        },
        "files": [
            "AGENTS.md",
            "CLAUDE.md",
            "opencode.json",
            "docs",
            "rules",
            "skills",
            "agents",
            ".claude-plugin",
            ".codex-plugin",
            "framework",
            "bin",
            "lib",
            "README.md",
            "LICENSE",
        ],
        "bin": {
            "aqp": "bin/aqp.mjs",
        },
    }
    return json.dumps(package_manifest, indent=2) + "\n"


def _render_package_readme(distribution_spec: dict[str, Any]) -> str:
    package_name = distribution_spec["name"]
    return "\n".join(
        [
            f"# {package_name}",
            "",
            distribution_spec["description"],
            "",
            "## Install",
            "",
            f"```bash\nnpx {package_name} install\n```",
            "",
            "The installer asks which supported tools should be configured and whether it may manage each global root entrypoint.",
            "",
            "Supported tools:",
            "",
            "- Claude Code",
            "- Codex",
            "- OpenCode",
            "",
            "## Source",
            "",
            distribution_spec["homepage"],
            "",
        ]
    )


def _render_package_license(distribution_spec: dict[str, Any]) -> str:
    author_name = distribution_spec["author"]["name"]
    return "\n".join(
        [
            "MIT License",
            "",
            f"Copyright (c) {author_name}",
            "",
            "Permission is hereby granted, free of charge, to any person obtaining a copy",
            "of this software and associated documentation files (the \"Software\"), to deal",
            "in the Software without restriction, including without limitation the rights",
            "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell",
            "copies of the Software, and to permit persons to whom the Software is",
            "furnished to do so, subject to the following conditions:",
            "",
            "The above copyright notice and this permission notice shall be included in all",
            "copies or substantial portions of the Software.",
            "",
            "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR",
            "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,",
            "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE",
            "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER",
            "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,",
            "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE",
            "SOFTWARE.",
            "",
        ]
    )


def _render_publish_workflow(distribution_spec: dict[str, Any]) -> str:
    package_name = distribution_spec["name"]
    return "\n".join(
        [
            "name: Publish Package",
            "",
            "on:",
            "  workflow_dispatch:",
            "  push:",
            "    tags:",
            '      - "plugin-v*"',
            "",
            "jobs:",
            "  publish:",
            "    runs-on: ubuntu-latest",
            "    permissions:",
            "      contents: read",
            "      id-token: write",
            "    steps:",
            "      - name: Checkout",
            "        uses: actions/checkout@v6",
            "      - name: Setup Python",
            "        uses: actions/setup-python@v6",
            "        with:",
            '          python-version: "3.12"',
            "      - name: Setup Node",
            "        uses: actions/setup-node@v6",
            "        with:",
            '          node-version: "24"',
            '          registry-url: "https://registry.npmjs.org"',
            "      - name: Read package version",
            "        id: package",
            "        run: |",
            f"          VERSION=$(node -p \"require('./plugins/{package_name}/package.json').version\")",
            "          echo \"version=$VERSION\" >> \"$GITHUB_OUTPUT\"",
            "      - name: Read published version",
            "        id: published",
            f"        run: echo \"version=$(npm view {package_name} version 2>/dev/null || true)\" >> \"$GITHUB_OUTPUT\"",
            "      - name: Build framework",
            "        run: python3 scripts/build_framework.py",
            "      - name: Validate framework",
            "        run: python3 scripts/validate_framework.py",
            "      - name: Run Python tests",
            "        run: python3 -m unittest tests/test_framework_tools.py",
            "      - name: Run Node tests",
            "        run: node --test tests/node/install.test.mjs",
            "      - name: Publish package",
            "        if: steps.package.outputs.version != steps.published.outputs.version",
            f"        run: npm publish --access public\n        working-directory: plugins/{package_name}",
            "        env:",
            "          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}",
            "      - name: Skip publish when version already exists",
            "        if: steps.package.outputs.version == steps.published.outputs.version",
            "        run: echo \"Package version already published; skipping npm publish.\"",
            "",
        ]
    )


def _render_template(content: str, replacements: dict[str, str]) -> str:
    rendered = content
    while True:
        updated = rendered
        for key, value in replacements.items():
            updated = updated.replace(f"{{{{{key}}}}}", value)
        if updated == rendered:
            return updated
        rendered = updated


def _entrypoint_replacements(*, quality_definition_path: str, workflow_path: str, primary_skill_root: str, skill_root: str, system_layout_path: str, priority_body: str, startup_sequence_body: str, skill_routing_body: str, quality_rules_body: str, review_flow_body: str) -> dict[str, str]:
    return {
        "quality_definition_path": quality_definition_path,
        "workflow_path": workflow_path,
        "primary_skill_root": primary_skill_root,
        "quality_index_skill_path": f"{skill_root}/quality-index/SKILL.md",
        "grounding_first_skill_path": f"{skill_root}/grounding-first/SKILL.md",
        "typescript_zero_bypass_skill_path": f"{skill_root}/typescript-zero-bypass/SKILL.md",
        "vite_vitest_tdd_skill_path": f"{skill_root}/vite-vitest-tdd/SKILL.md",
        "react_public_api_testing_skill_path": f"{skill_root}/react-public-api-testing/SKILL.md",
        "anti_bypass_audit_skill_path": f"{skill_root}/anti-bypass-audit/SKILL.md",
        "refactoring_with_safety_skill_path": f"{skill_root}/refactoring-with-safety/SKILL.md",
        "governance_installation_skill_path": f"{skill_root}/governance-installation/SKILL.md",
        "system_layout_path": system_layout_path,
        "priority_body": priority_body,
        "startup_sequence_body": startup_sequence_body,
        "skill_routing_body": skill_routing_body,
        "quality_rules_body": quality_rules_body,
        "review_flow_body": review_flow_body,
    }


def _repo_policy_sections() -> dict[str, str]:
    return {
        "priority_body": "\n".join(
            [
                "- Instruções diretas de sistema, desenvolvedor e usuário sobrepõem este arquivo.",
                "- [`docs/policy/quality-definition.md`]({{quality_definition_path}}) é a definição canônica de qualidade neste repositório.",
                "- Se qualquer skill, rule, exemplo ou prompt de agent contradiz a definição de qualidade, a definição de qualidade vence.",
                "- Projeções geradas não devem virar fonte de verdade.",
                "- Dados de treinamento não são fonte de verdade. Verifique cada afirmação não trivial com ferramenta antes de agir.",
                "- Não modifique configuração global, estado de diretório home, contas ou ferramentas fora deste repositório sem permissão explícita do usuário.",
                "- Não publique releases, tags, pacotes ou outros efeitos externos sem permissão explícita do usuário.",
            ]
        ),
        "startup_sequence_body": "\n".join(
            [
                "1. Confirme literalmente o pedido do usuário; se ambíguo, pergunte antes de começar.",
                "2. Leia [quality-definition]({{quality_definition_path}}).",
                "3. Leia [workflow]({{workflow_path}}).",
                "4. Carregue o menor conjunto relevante de skills a partir de `{{primary_skill_root}}`.",
                "5. Para mudanças de código, o agent principal coordena; a execução deve passar por `implementer`.",
                "6. Execute com TDD quando testes forem viáveis.",
                "7. Rode os agents de auditoria correspondentes antes da aprovação final.",
            ]
        ),
        "skill_routing_body": "\n".join(
            [
                "- Use [grounding-first]({{grounding_first_skill_path}}) sempre que a tarefa exigir afirmação factual sobre repositório, biblioteca ou intenção do usuário.",
                "- Use [quality-index]({{quality_index_skill_path}}) primeiro quando a tarefa cruza múltiplas áreas.",
                "- Use [typescript-zero-bypass]({{typescript_zero_bypass_skill_path}}) para qualquer mudança em `.ts` ou `.tsx`.",
                "- Use [vite-vitest-tdd]({{vite_vitest_tdd_skill_path}}) ao trabalhar com Vite, Vitest ou TDD unitário/componente.",
                "- Use [react-public-api-testing]({{react_public_api_testing_skill_path}}) para testes de comportamento de componente React.",
                "- Use [anti-bypass-audit]({{anti_bypass_audit_skill_path}}) ao revisar diffs, helpers suspeitos ou configs enfraquecidas.",
                "- Use [refactoring-with-safety]({{refactoring_with_safety_skill_path}}) para refactors que não são bug fix puro.",
                "- Use [governance-installation]({{governance_installation_skill_path}}) ao instalar ou atualizar este framework em outro repositório.",
            ]
        ),
        "quality_rules_body": "\n".join(
            [
                "- TDD é obrigatório quando testes são tecnicamente viáveis.",
                "- Suíte verde sem prova de comportamento não é build verde.",
                "- `any`, type assertions, non-null assertions, bypasses por ts-comment e enfraquecimento de lint/config são falhas automáticas.",
                "- Use `?` para parâmetros e propriedades omitíveis; não escreva `T | undefined` em assinaturas de parâmetro ou propriedade omitíveis.",
                "- Contratos públicos devem manter uma forma estável de topo; não retorne uniões como `T[] | { data: T[]; total: number }`.",
                "- Arquivos de responsabilidade única são exigidos: uma classe por arquivo sem funções de topo irmãs, ou múltiplas funções exportadas apenas quando o nome do arquivo nomeia uma responsabilidade compartilhada.",
                "- Nomes genéricos como `helpers.ts`, `utils.ts`, `common.ts` ou `shared.ts` são falhas automáticas quando escondem a razão para mudar.",
                "- Quando houver mudança de código, a execução deve passar pelo `implementer`; edição direta pelo agent principal é bloqueio.",
                "- `Map` em contratos públicos ou de domínio é suspeito por padrão e deve ser tratado como bypass de modelagem a menos que uma regra mais forte do repositório permita explicitamente.",
                "- Helpers, factories, mocks, branches ou narrowing adicionados apenas para silenciar o sistema de tipos ou facilitar testes são falhas automáticas.",
                "- Zod é permitido apenas em fronteiras de input externo.",
                "- Joi é permitido apenas para validação de ambiente quando realmente necessário.",
                "- Tipos nomeados fortes são exigidos.",
                "- Tipos estruturais inline são proibidos.",
                "- Não invente arquivos, APIs, imports, chaves de config ou comportamento de biblioteca; verifique com ferramenta primeiro.",
                "- Quando incerto, pare e pergunte ao usuário em vez de adivinhar.",
                "- Cite a fonte (`arquivo:linha`, URL oficial ou quote literal do usuário) para cada escolha não trivial de implementação.",
                "- Revisores devem rejeitar diffs suspeitos em vez de \"aceitar com ressalvas\".",
            ]
        ),
        "review_flow_body": "\n".join(
            [
                "- Corrija o problema raiz, não o sintoma.",
                "- Mantenha testes diretos, curtos e baseados em comportamento.",
                "- Prefira nomes de domínio explícitos em vez de utils genéricos.",
                "- Mantenha o texto da política severo e acionável; não amoleça a linguagem para preservar conforto do agent.",
                "- Após qualquer mudança em fontes canônicas como `framework/skills/`, `framework/rules/`, `docs/policy/` ou `framework/agents/specs/`, rode `python3 scripts/build_framework.py` antes de declarar o repositório consistente.",
                "- Depois do build, rode `python3 scripts/validate_framework.py`. Se scripts mudaram, rode `python3 -m unittest tests/test_framework_tools.py` e `node --test tests/node/install.test.mjs`.",
                "- Antes de commit, push, merge request, release ou aprovação, valide os receipts exigidos em `.aqp/receipts/`.",
                "- Use `bypass-auditor` para tipagem, config, mocks, helpers ou diffs suspeitos.",
                "- Use `tdd-warden` quando comportamento ou testes mudaram ou deveriam ter mudado.",
                "- Use `pr-gatekeeper` apenas para revisão final de aprovar ou rejeitar.",
            ]
        ),
    }


def _global_policy_sections() -> dict[str, str]:
    return {
        "priority_body": "\n".join(
            [
                "- Instruções diretas de sistema, desenvolvedor e usuário sobrepõem este arquivo.",
                "- Prefira código local atual e documentação oficial atual sobre memória.",
                "- Dados de treinamento não são fonte de verdade; verifique cada afirmação não trivial com ferramenta ou cite a instrução literal do usuário.",
                "- Trate as skills e auditores exigidos neste arquivo como requisitos de workflow obrigatórios.",
            ]
        ),
        "startup_sequence_body": "\n".join(
            [
                "1. Confirme literalmente o pedido do usuário; se ambíguo, pergunte antes de começar.",
                "2. Leia [quality-definition]({{quality_definition_path}}) quando a tarefa precisar de contexto de política do repositório.",
                "3. Leia [workflow]({{workflow_path}}) quando o repositório definir um.",
                "4. Carregue o menor conjunto de skills exigido a partir de `{{primary_skill_root}}` antes de propor edits ou escrever código.",
                "5. Para mudanças de código, o agent principal coordena; a execução deve passar por `implementer`.",
            ]
        ),
        "skill_routing_body": "\n".join(
            [
                "- Use [grounding-first]({{grounding_first_skill_path}}) sempre que a tarefa exigir afirmação factual sobre repositório, biblioteca ou intenção do usuário.",
                "- Use [quality-index]({{quality_index_skill_path}}) quando a tarefa cruza múltiplas áreas ou quando estiver em dúvida sobre quais validadores aplicar.",
                "- Use [typescript-zero-bypass]({{typescript_zero_bypass_skill_path}}) para mudanças em `.ts` ou `.tsx`.",
                "- Use [vite-vitest-tdd]({{vite_vitest_tdd_skill_path}}) para TDD em Vite ou Vitest.",
                "- Use [react-public-api-testing]({{react_public_api_testing_skill_path}}) para testes de comportamento em React.",
                "- Use [anti-bypass-audit]({{anti_bypass_audit_skill_path}}) ao revisar diffs, helpers suspeitos, configs enfraquecidas ou mudanças pesadas em tipagem/config.",
                "- Use [refactoring-with-safety]({{refactoring_with_safety_skill_path}}) para refactors que não são bug fix puro.",
                "- Use [governance-installation]({{governance_installation_skill_path}}) ao instalar ou atualizar este pacote de governança.",
            ]
        ),
        "quality_rules_body": "\n".join(
            [
                "- Carregue as skills exigidas antes de propor edits ou escrever código.",
                "- Se uma skill exigida não estiver disponível no runtime atual, pare e reporte `BLOCKED`.",
                "- Use testes behavior-first quando testes forem viáveis.",
                "- Evite bypasses de tipo, bypasses por comentário, enfraquecimento de config e verdes falsos.",
                "- Use `?` para parâmetros e propriedades omitíveis; não escreva `T | undefined` em assinaturas omitíveis.",
                "- Contratos públicos devem manter uma forma estável de topo; não retorne uniões como `T[] | { data: T[]; total: number }`.",
                "- Arquivos de responsabilidade única são exigidos: uma classe por arquivo sem funções de topo irmãs, ou múltiplas funções exportadas apenas quando o nome do arquivo nomeia uma responsabilidade compartilhada.",
                "- Nomes genéricos como `helpers.ts`, `utils.ts`, `common.ts` ou `shared.ts` são falhas automáticas quando escondem a razão para mudar.",
                "- Quando houver mudança de código, a execução deve passar pelo `implementer`; edição direta pelo agent principal é bloqueio.",
                "- Não invente arquivos, APIs, imports, chaves de config ou comportamento de biblioteca; verifique com ferramenta primeiro.",
                "- Quando incerto, pare e pergunte ao usuário em vez de adivinhar.",
                "- Cite a fonte (`arquivo:linha`, URL oficial ou quote literal do usuário) para cada escolha não trivial de implementação.",
                "- Prefira tipos nomeados e modelos explícitos em vez de atalhos estruturais inline.",
            ]
        ),
        "review_flow_body": "\n".join(
            [
                "- Para mudanças de código, execute a implementação via `implementer`; o agent principal coordena, não substitui esse papel.",
                "- Para mudanças de código, invoque explicitamente os auditores exigidos antes da aprovação final.",
                "- Para mudanças de código, não finalize até que os auditores exigidos tenham rodado e seus resultados tenham sido revisados.",
                "- Não substitua invocação de agent de auditoria nominal por autorreview inline.",
                "- Antes de commit, push, merge request, release ou aprovação, valide os receipts exigidos em `.aqp/receipts/`.",
                "- Para tipagem, config, mocks, helpers ou diffs suspeitos, rode `bypass-auditor`.",
                "- Para mudanças de comportamento ou bug fixes, rode `tdd-warden` e `bypass-auditor`.",
                "- Para aprovação final, release ou decisão de merge, rode `pr-gatekeeper` após os demais auditores exigidos.",
                "- Se `implementer`, algum auditor exigido, ou a validação de receipts não puder rodar no runtime atual, pare e reporte `BLOCKED`.",
            ]
        ),
    }


def _render_agents_md(entrypoint_policy: str, replacements: dict[str, str]) -> str:
    return "# AGENTS.md\n\n" + _render_template(entrypoint_policy, replacements).rstrip() + "\n"


def _render_repo_claude_md() -> str:
    return "@AGENTS.md\n"


def _render_packaged_claude_md(entrypoint_policy: str, replacements: dict[str, str]) -> str:
    rendered_policy = _render_template(entrypoint_policy, replacements)
    return "\n".join(["# CLAUDE.md", "", rendered_policy.rstrip(), ""])


def _render_opencode_config(opencode_config: dict[str, Any]) -> str:
    return json.dumps(opencode_config, indent=2) + "\n"


def build_entrypoint_projections(root: Path, entrypoint_policy: str | None = None, opencode_config: dict[str, Any] | None = None) -> list[str]:
    resolved_entrypoint_policy = (
        entrypoint_policy if entrypoint_policy is not None else _load_entrypoint_policy(root, required=True)
    )
    resolved_opencode_config = (
        opencode_config if opencode_config is not None else _load_entrypoint_opencode_config(root, required=True)
    )
    assert resolved_entrypoint_policy is not None
    assert resolved_opencode_config is not None
    repo_replacements = _entrypoint_replacements(
        quality_definition_path="docs/policy/quality-definition.md",
        workflow_path="docs/policy/workflow.md",
        primary_skill_root="framework/skills/",
        skill_root="framework/skills",
        system_layout_path="docs/policy/system-layout.md",
        **_repo_policy_sections(),
    )

    _write_text(root / "AGENTS.md", _render_agents_md(resolved_entrypoint_policy, repo_replacements))
    return ["AGENTS.md"]


def _render_claude_plugin_manifest(distribution_spec: dict[str, Any]) -> str:
    manifest = {
        "name": distribution_spec["name"],
        "version": distribution_spec["version"],
        "description": distribution_spec["description"],
        "author": distribution_spec["author"],
        "homepage": distribution_spec["homepage"],
        "repository": distribution_spec["repository"],
        "license": distribution_spec["license"],
        "keywords": distribution_spec["keywords"],
        "skills": "./skills",
        "agents": "./agents",
    }
    return json.dumps(manifest, indent=2) + "\n"


def _render_codex_plugin_manifest(distribution_spec: dict[str, Any]) -> str:
    manifest = {
        "name": distribution_spec["name"],
        "version": distribution_spec["version"],
        "description": distribution_spec["description"],
        "author": distribution_spec["author"],
        "homepage": distribution_spec["homepage"],
        "repository": distribution_spec["repository"],
        "license": distribution_spec["license"],
        "keywords": distribution_spec["keywords"],
        "skills": "./skills",
        "interface": distribution_spec["codexInterface"],
    }
    return json.dumps(manifest, indent=2) + "\n"


def _render_claude_marketplace(distribution_spec: dict[str, Any]) -> str:
    marketplace = distribution_spec["claudeMarketplace"]
    entry = {
        "name": distribution_spec["name"],
        "source": "./plugins/" + distribution_spec["name"],
        "description": distribution_spec["description"],
        "version": distribution_spec["version"],
        "author": distribution_spec["author"],
        "homepage": distribution_spec["homepage"],
        "repository": distribution_spec["repository"],
        "license": distribution_spec["license"],
        "keywords": distribution_spec["keywords"],
        "category": "Coding",
    }
    rendered = {
        "name": marketplace["name"],
        "owner": marketplace["owner"],
        "metadata": marketplace["metadata"],
        "plugins": [entry],
    }
    return json.dumps(rendered, indent=2) + "\n"


def _render_codex_marketplace(distribution_spec: dict[str, Any]) -> str:
    marketplace = distribution_spec["codexMarketplace"]
    entry = {
        "name": distribution_spec["name"],
        "source": {
            "source": "local",
            "path": "./plugins/" + distribution_spec["name"],
        },
        "policy": marketplace["policy"],
        "category": marketplace["category"],
    }
    rendered = {
        "name": marketplace["name"],
        "interface": marketplace["interface"],
        "plugins": [entry],
    }
    return json.dumps(rendered, indent=2) + "\n"


def build_plugin_distribution(root: Path, distribution_spec: dict[str, Any] | None = None) -> list[str]:
    resolved_distribution_spec = (
        distribution_spec if distribution_spec is not None else _load_distribution_spec(root, required=True)
    )
    assert resolved_distribution_spec is not None
    resolved_entrypoint_policy = _load_entrypoint_policy(root, required=True)
    resolved_opencode_config = _load_entrypoint_opencode_config(root, required=True)
    assert resolved_entrypoint_policy is not None
    assert resolved_opencode_config is not None

    plugin_root = root / "plugins" / resolved_distribution_spec["name"]
    _reset_directory(plugin_root)

    package_replacements = _entrypoint_replacements(
        quality_definition_path="docs/policy/quality-definition.md",
        workflow_path="docs/policy/workflow.md",
        primary_skill_root="skills/",
        skill_root="skills",
        system_layout_path="docs/policy/system-layout.md",
        **_global_policy_sections(),
    )
    package_agents_replacements = _entrypoint_replacements(
        quality_definition_path="docs/policy/quality-definition.md",
        workflow_path="docs/policy/workflow.md",
        primary_skill_root="skills/",
        skill_root="skills",
        system_layout_path="docs/policy/system-layout.md",
        **_global_policy_sections(),
    )

    copy_paths = [
        Path("docs") / "policy",
        Path("framework") / "entrypoints",
        Path("framework") / "agents" / "specs",
        Path("framework") / "agents" / "prompts",
    ]
    for relative_path in copy_paths:
        source = root / relative_path
        if source.exists():
            _copy_path(source, plugin_root / relative_path)

    _copy_path(root / "framework" / "package" / "bin", plugin_root / "bin")
    _copy_path(root / "framework" / "package" / "lib", plugin_root / "lib")

    rules_root = root / "framework" / "rules"
    if rules_root.exists():
        _copy_path(rules_root, plugin_root / "rules")

    source_skills = _load_skill_sources(root, required=True)
    for source_skill in source_skills:
        _copy_path(source_skill, plugin_root / "skills" / source_skill.name)

    for spec in _load_agent_specs(root, required=True):
        name = spec["name"]
        _write_text(plugin_root / "agents" / f"{name}.md", _render_claude_agent(spec))

    _write_text(plugin_root / "CLAUDE.md", _render_packaged_claude_md(resolved_entrypoint_policy, package_replacements))
    _write_text(plugin_root / "AGENTS.md", _render_agents_md(resolved_entrypoint_policy, package_agents_replacements))
    _write_text(plugin_root / "opencode.json", _render_opencode_config(resolved_opencode_config))
    _write_text(plugin_root / "README.md", _render_package_readme(resolved_distribution_spec))
    _write_text(plugin_root / "LICENSE", _render_package_license(resolved_distribution_spec))
    _write_text(plugin_root / "package.json", _render_generated_package_json(resolved_distribution_spec))
    _write_text(
        plugin_root / ".claude-plugin" / "plugin.json",
        _render_claude_plugin_manifest(resolved_distribution_spec),
    )
    _write_text(
        plugin_root / ".codex-plugin" / "plugin.json",
        _render_codex_plugin_manifest(resolved_distribution_spec),
    )
    _write_text(root / ".github" / "workflows" / "publish-package.yml", _render_publish_workflow(resolved_distribution_spec))

    return [resolved_distribution_spec["name"]]


def _iter_text_files(root: Path) -> list[Path]:
    text_paths: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if ".git" in path.parts:
            continue
        if path.suffix in {".md", ".json", ".py", ".toml", ".txt", ".ts", ".tsx"} or path.name == "SKILL.md":
            text_paths.append(path)
    return sorted(text_paths)


def _relative_file_set(root: Path) -> set[Path]:
    files: set[Path] = set()
    for path in root.rglob("*"):
        if path.is_file():
            files.add(path.relative_to(root))
    return files


def _expected_agent_projections(root: Path) -> dict[Path, str]:
    expected: dict[Path, str] = {}
    for spec in _load_agent_specs(root, required=False):
        name = spec["name"]
        expected[Path(".claude") / "agents" / f"{name}.md"] = _normalized_output(_render_claude_agent(spec))
        expected[Path(".opencode") / "agents" / f"{name}.md"] = _normalized_output(_render_opencode_agent(spec))
        expected[Path(".codex") / "agents" / f"{name}.toml"] = _normalized_output(_render_codex_agent(spec))
    return expected


def _expected_entrypoint_projections(root: Path) -> dict[Path, str]:
    entrypoint_policy = _load_entrypoint_policy(root, required=False)
    if entrypoint_policy is None:
        return {}
    repo_replacements = _entrypoint_replacements(
        quality_definition_path="docs/policy/quality-definition.md",
        workflow_path="docs/policy/workflow.md",
        primary_skill_root="framework/skills/",
        skill_root="framework/skills",
        system_layout_path="docs/policy/system-layout.md",
        **_repo_policy_sections(),
    )
    return {
        Path("AGENTS.md"): _normalized_output(_render_agents_md(entrypoint_policy, repo_replacements)),
    }


def _expected_plugin_distribution(root: Path) -> dict[Path, str]:
    distribution_spec = _load_distribution_spec(root, required=False)
    entrypoint_policy = _load_entrypoint_policy(root, required=False)
    opencode_config = _load_entrypoint_opencode_config(root, required=False)
    if distribution_spec is None or entrypoint_policy is None or opencode_config is None:
        return {}

    expected: dict[Path, str] = {}
    plugin_root = Path("plugins") / distribution_spec["name"]
    package_replacements = _entrypoint_replacements(
        quality_definition_path="docs/policy/quality-definition.md",
        workflow_path="docs/policy/workflow.md",
        primary_skill_root="skills/",
        skill_root="skills",
        system_layout_path="docs/policy/system-layout.md",
        **_global_policy_sections(),
    )
    package_agents_replacements = _entrypoint_replacements(
        quality_definition_path="docs/policy/quality-definition.md",
        workflow_path="docs/policy/workflow.md",
        primary_skill_root="skills/",
        skill_root="skills",
        system_layout_path="docs/policy/system-layout.md",
        **_global_policy_sections(),
    )
    expected[plugin_root / "package.json"] = _normalized_output(_render_generated_package_json(distribution_spec))
    expected[plugin_root / "README.md"] = _normalized_output(_render_package_readme(distribution_spec))
    expected[plugin_root / "LICENSE"] = _normalized_output(_render_package_license(distribution_spec))
    expected[plugin_root / ".claude-plugin" / "plugin.json"] = _normalized_output(
        _render_claude_plugin_manifest(distribution_spec)
    )
    expected[plugin_root / ".codex-plugin" / "plugin.json"] = _normalized_output(
        _render_codex_plugin_manifest(distribution_spec)
    )
    expected[Path(".github") / "workflows" / "publish-package.yml"] = _normalized_output(
        _render_publish_workflow(distribution_spec)
    )
    copied_roots = [
        Path("docs") / "policy",
        Path("framework") / "entrypoints",
        Path("framework") / "agents" / "specs",
        Path("framework") / "agents" / "prompts",
    ]
    expected[plugin_root / "CLAUDE.md"] = _normalized_output(
        _render_packaged_claude_md(entrypoint_policy, package_replacements)
    )
    expected[plugin_root / "AGENTS.md"] = _normalized_output(
        _render_agents_md(entrypoint_policy, package_agents_replacements)
    )
    expected[plugin_root / "opencode.json"] = _normalized_output(_render_opencode_config(opencode_config))
    for relative_root in copied_roots:
        source = root / relative_root
        if source.is_file():
            expected[plugin_root / relative_root] = _normalized_output(source.read_text(encoding="utf-8"))
            continue
        if not source.exists():
            continue
        for path in source.rglob("*"):
            if not path.is_file():
                continue
            expected[plugin_root / path.relative_to(root)] = _normalized_output(path.read_text(encoding="utf-8"))

    package_source_roots = [
        (root / "framework" / "package" / "bin", plugin_root / "bin"),
        (root / "framework" / "package" / "lib", plugin_root / "lib"),
    ]
    for source_root, destination_root in package_source_roots:
        if not source_root.exists():
            continue
        for path in source_root.rglob("*"):
            if not path.is_file():
                continue
            expected[destination_root / path.relative_to(source_root)] = _normalized_output(
                path.read_text(encoding="utf-8")
            )

    rules_root = root / "framework" / "rules"
    if rules_root.exists():
        for path in rules_root.rglob("*"):
            if not path.is_file():
                continue
            expected[plugin_root / "rules" / path.relative_to(rules_root)] = _normalized_output(
                path.read_text(encoding="utf-8")
            )

    for source_skill in _load_skill_sources(root, required=False):
        for path in source_skill.rglob("*"):
            if not path.is_file():
                continue
            relative = path.relative_to(source_skill)
            expected[plugin_root / "skills" / source_skill.name / relative] = _normalized_output(
                path.read_text(encoding="utf-8")
            )

    for spec in _load_agent_specs(root, required=False):
        name = spec["name"]
        expected[plugin_root / "agents" / f"{name}.md"] = _normalized_output(_render_claude_agent(spec))

    return expected


def _check_local_links(root: Path, path: Path, content: str) -> list[str]:
    errors: list[str] = []
    for _, target in LOCAL_LINK_PATTERN.findall(content):
        if target.startswith(("http://", "https://", "mailto:", "#")):
            continue
        normalized_target = target.split("#", 1)[0]
        candidate = (path.parent / normalized_target).resolve()
        if not candidate.exists():
            errors.append(f"Broken link in {path.relative_to(root)} -> {target}")
    for include_target in AT_INCLUDE_PATTERN.findall(content):
        candidate = (path.parent / include_target).resolve()
        if not candidate.exists():
            errors.append(f"Broken include in {path.relative_to(root)} -> @{include_target}")
    return errors


def _is_entrypoint_template(path: Path, content: str) -> bool:
    return "framework" in path.parts and "entrypoints" in path.parts and bool(ENTRYPOINT_TEMPLATE_PATTERN.search(content))


def validate_repository(root: Path) -> ValidationResult:
    errors: list[str] = []
    warnings: list[str] = []

    required_files = [
        root / "README.md",
        root / "AGENTS.md",
        root / "docs" / "policy" / "quality-definition.md",
    ]
    for path in required_files:
        if not path.exists():
            errors.append(f"Missing required file: {path.relative_to(root)}")

    for path in _iter_text_files(root):
        content = path.read_text(encoding="utf-8")
        if PLACEHOLDER_PATTERN.search(content):
            errors.append(f"Placeholder token found in {path.relative_to(root)}")
        if path.suffix in {".md", ".json", ".toml"} and (
            "REPO_NAME=" in content or "REPO_DESCRIPTION=" in content
        ):
            errors.append(f"Unresolved repository placeholder found in {path.relative_to(root)}")
        if (path.suffix == ".md" or path.name == "SKILL.md") and not _is_entrypoint_template(path, content):
            errors.extend(_check_local_links(root, path, content))

    forbidden_root_paths = [
        root / ".claude",
        root / ".codex",
        root / ".opencode",
        root / ".agents",
        root / ".claude-plugin",
        root / "CLAUDE.md",
        root / "opencode.json",
    ]
    for forbidden_path in forbidden_root_paths:
        if forbidden_path.exists():
            errors.append(
                f"Tool-specific runtime path must not exist at repository root: {forbidden_path.relative_to(root)}"
            )

    expected_entrypoint_projections = _expected_entrypoint_projections(root)
    for relative_path, expected_content in expected_entrypoint_projections.items():
        actual_path = root / relative_path
        if not actual_path.exists():
            errors.append(f"Missing generated entrypoint file: {relative_path}")
            continue
        actual_content = actual_path.read_text(encoding="utf-8")
        if actual_content != expected_content:
            errors.append(
                "Generated entrypoint drift between canonical entrypoint sources and "
                f"{relative_path}"
            )

    expected_plugin_distribution = _expected_plugin_distribution(root)
    for relative_path, expected_content in expected_plugin_distribution.items():
        actual_path = root / relative_path
        if not actual_path.exists():
            errors.append(f"Missing generated plugin distribution file: {relative_path}")
            continue
        actual_content = actual_path.read_text(encoding="utf-8")
        if actual_content != expected_content:
            errors.append(
                "Generated plugin distribution drift between canonical sources and "
                f"{relative_path}"
            )

    return ValidationResult(errors=errors, warnings=warnings)


def build_all(root: Path) -> tuple[list[str], list[str], list[str], list[str]]:
    entrypoint_policy = _load_entrypoint_policy(root, required=True)
    assert entrypoint_policy is not None
    source_skills = _load_skill_sources(root, required=True)
    specs = _load_agent_specs(root, required=True)
    distribution_spec = _load_distribution_spec(root, required=True)
    entrypoints = build_entrypoint_projections(root, entrypoint_policy)
    skills = build_skill_projection(root, source_skills)
    agents = build_agent_projections(root, specs)
    distributions = build_plugin_distribution(root, distribution_spec)
    return entrypoints, skills, agents, distributions


def _default_root() -> Path:
    return Path(__file__).resolve().parent.parent


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build or validate the agent governance framework.")
    parser.add_argument("command", choices=("build", "validate"))
    parser.add_argument("--root", default=str(_default_root()))
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    if args.command == "build":
        try:
            entrypoints, skills, agents, distributions = build_all(root)
        except BuildError as error:
            print(f"ERROR: {error}")
            return 1
        print(
            " ".join(
                [
                    f"built-entrypoints={len(entrypoints)}",
                    f"built-skills={len(skills)}",
                    f"built-agents={len(agents)}",
                    f"built-distributions={len(distributions)}",
                ]
            )
        )
        return 0

    result = validate_repository(root)
    for warning in result.warnings:
        print(f"WARNING: {warning}")
    for error in result.errors:
        print(f"ERROR: {error}")
    if result.errors:
        return 1
    print("validation-ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
