from __future__ import annotations

import argparse
import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any


GENERATED_MARKER = "<!-- generated by scripts/build_framework.py; do not edit directly -->"
PLACEHOLDER_PATTERN = re.compile(r"^\s*(TODO|TBD)([:\s]|$)", re.IGNORECASE)
LOCAL_LINK_PATTERN = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
AT_INCLUDE_PATTERN = re.compile(r"(?m)^@([A-Za-z0-9_./-]+)$")


@dataclass(frozen=True)
class ValidationResult:
    errors: list[str]
    warnings: list[str]


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def _reset_directory(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def _quote_yaml(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _yaml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    rendered = str(value)
    if re.fullmatch(r"[A-Za-z0-9._/-]+", rendered):
        return rendered
    return _quote_yaml(rendered)


def _yaml_lines(data: dict[str, Any]) -> list[str]:
    lines: list[str] = ["---"]
    for key, value in data.items():
        if isinstance(value, list):
            lines.append(f"{key}:")
            for item in value:
                lines.append(f"  - {_yaml_scalar(item)}")
        elif isinstance(value, dict):
            lines.append(f"{key}:")
            for child_key, child_value in value.items():
                if isinstance(child_value, dict):
                    lines.append(f"  {child_key}:")
                    for grandchild_key, grandchild_value in child_value.items():
                        lines.append(f"    {grandchild_key}: {_yaml_scalar(grandchild_value)}")
                else:
                    lines.append(f"  {child_key}: {_yaml_scalar(child_value)}")
        else:
            lines.append(f"{key}: {_yaml_scalar(value)}")
    lines.append("---")
    return lines


def _toml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _readable_name(path: Path) -> str:
    return str(path).replace(str(path.parent.parent.parent), "", 1)


def build_skill_projection(root: Path) -> list[str]:
    source_root = root / ".claude" / "skills"
    destination_root = root / ".agents" / "skills"
    _reset_directory(destination_root)

    if not source_root.exists():
        return []

    built_skills: list[str] = []
    for source_skill in sorted(path for path in source_root.iterdir() if path.is_dir()):
        destination_skill = destination_root / source_skill.name
        shutil.copytree(source_skill, destination_skill)
        built_skills.append(source_skill.name)
    return built_skills


def _load_agent_specs(root: Path) -> list[dict[str, Any]]:
    spec_root = root / "framework" / "agents" / "specs"
    if not spec_root.exists():
        return []
    specs: list[dict[str, Any]] = []
    for path in sorted(spec_root.glob("*.json")):
        spec = _load_json(path)
        prompt_path = spec.get("promptPath")
        if prompt_path is not None:
            resolved_prompt = (root / prompt_path).read_text(encoding="utf-8").rstrip()
            spec["prompt"] = resolved_prompt
        specs.append(spec)
    return specs


def _render_claude_agent(spec: dict[str, Any]) -> str:
    claude = spec["claude"]
    frontmatter: dict[str, Any] = {
        "name": spec["name"],
        "description": spec["description"],
    }
    for field in ("tools", "disallowedTools", "model", "permissionMode", "maxTurns", "skills"):
        if field in claude:
            frontmatter[field] = claude[field]
    return "\n".join([GENERATED_MARKER, *_yaml_lines(frontmatter), spec["prompt"]])


def _render_opencode_agent(spec: dict[str, Any]) -> str:
    opencode = spec["opencode"]
    frontmatter: dict[str, Any] = {
        "description": spec["description"],
        "mode": opencode["mode"],
    }
    for field in ("model", "temperature", "steps", "permission"):
        if field in opencode:
            frontmatter[field] = opencode[field]
    return "\n".join([GENERATED_MARKER, *_yaml_lines(frontmatter), spec["prompt"]])


def _render_codex_agent(spec: dict[str, Any]) -> str:
    codex = spec["codex"]
    lines = [
        f"# generated by scripts/build_framework.py; do not edit directly",
        f'name = "{spec["name"]}"',
        f'description = "{spec["description"]}"',
    ]
    for field in ("model", "model_reasoning_effort", "sandbox_mode"):
        if field in codex:
            lines.append(f'{field} = {_toml_scalar(codex[field])}')
    instructions = spec["prompt"].replace('"""', '\\"\\"\\"')
    lines.append('developer_instructions = """')
    lines.append(instructions)
    lines.append('"""')
    return "\n".join(lines)


def build_agent_projections(root: Path) -> list[str]:
    specs = _load_agent_specs(root)
    built_agents: list[str] = []

    claude_root = root / ".claude" / "agents"
    opencode_root = root / ".opencode" / "agents"
    codex_root = root / ".codex" / "agents"
    _reset_directory(claude_root)
    _reset_directory(opencode_root)
    _reset_directory(codex_root)

    for spec in specs:
        name = spec["name"]
        _write_text(claude_root / f"{name}.md", _render_claude_agent(spec))
        _write_text(opencode_root / f"{name}.md", _render_opencode_agent(spec))
        _write_text(codex_root / f"{name}.toml", _render_codex_agent(spec))
        built_agents.append(name)
    return built_agents


def _iter_text_files(root: Path) -> list[Path]:
    text_paths: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if ".git" in path.parts:
            continue
        if path.suffix in {".md", ".json", ".py", ".toml", ".txt", ".ts", ".tsx"} or path.name == "SKILL.md":
            text_paths.append(path)
    return sorted(text_paths)


def _relative_file_set(root: Path) -> set[Path]:
    files: set[Path] = set()
    for path in root.rglob("*"):
        if path.is_file():
            files.add(path.relative_to(root))
    return files


def _check_local_links(root: Path, path: Path, content: str) -> list[str]:
    errors: list[str] = []
    for _, target in LOCAL_LINK_PATTERN.findall(content):
        if target.startswith(("http://", "https://", "mailto:", "#")):
            continue
        normalized_target = target.split("#", 1)[0]
        candidate = (path.parent / normalized_target).resolve()
        if not candidate.exists():
            errors.append(f"Broken link in {path.relative_to(root)} -> {target}")
    for include_target in AT_INCLUDE_PATTERN.findall(content):
        candidate = (path.parent / include_target).resolve()
        if not candidate.exists():
            errors.append(f"Broken include in {path.relative_to(root)} -> @{include_target}")
    return errors


def validate_repository(root: Path) -> ValidationResult:
    errors: list[str] = []
    warnings: list[str] = []

    required_files = [
        root / "README.md",
        root / "AGENTS.md",
        root / "CLAUDE.md",
        root / "docs" / "policy" / "quality-definition.md",
    ]
    for path in required_files:
        if not path.exists():
            errors.append(f"Missing required file: {path.relative_to(root)}")

    for path in _iter_text_files(root):
        content = path.read_text(encoding="utf-8")
        if PLACEHOLDER_PATTERN.search(content):
            errors.append(f"Placeholder token found in {path.relative_to(root)}")
        if path.suffix in {".md", ".json", ".toml"} and (
            "REPO_NAME=" in content or "REPO_DESCRIPTION=" in content
        ):
            errors.append(f"Unresolved repository placeholder found in {path.relative_to(root)}")
        if path.suffix == ".md" or path.name == "SKILL.md":
            errors.extend(_check_local_links(root, path, content))

    claude_skills_root = root / ".claude" / "skills"
    agents_skills_root = root / ".agents" / "skills"
    if claude_skills_root.exists():
        claude_skill_names = sorted(path.name for path in claude_skills_root.iterdir() if path.is_dir())
        agents_skill_names = (
            sorted(path.name for path in agents_skills_root.iterdir() if path.is_dir())
            if agents_skills_root.exists()
            else []
        )
        if claude_skill_names != agents_skill_names:
            errors.append("Skill projection mismatch between .claude/skills and .agents/skills")
        else:
            claude_skill_files = _relative_file_set(claude_skills_root)
            agents_skill_files = _relative_file_set(agents_skills_root)
            if claude_skill_files != agents_skill_files:
                errors.append("Skill projection file set mismatch between .claude/skills and .agents/skills")
            else:
                for relative_path in sorted(claude_skill_files):
                    claude_content = (claude_skills_root / relative_path).read_text(encoding="utf-8")
                    agents_content = (agents_skills_root / relative_path).read_text(encoding="utf-8")
                    if claude_content != agents_content:
                        errors.append(
                            "Skill projection content drift between "
                            f".claude/skills/{relative_path} and .agents/skills/{relative_path}"
                        )

    specs = _load_agent_specs(root)
    if specs:
        for spec in specs:
            name = spec["name"]
            expected_paths = [
                root / ".claude" / "agents" / f"{name}.md",
                root / ".opencode" / "agents" / f"{name}.md",
                root / ".codex" / "agents" / f"{name}.toml",
            ]
            for expected_path in expected_paths:
                if not expected_path.exists():
                    errors.append(f"Missing generated agent file: {expected_path.relative_to(root)}")
            claude_agent_path = root / ".claude" / "agents" / f"{name}.md"
            if claude_agent_path.exists():
                claude_agent_content = claude_agent_path.read_text(encoding="utf-8")
                if GENERATED_MARKER not in claude_agent_content:
                    warnings.append(f"Claude agent is missing generated marker: {claude_agent_path.relative_to(root)}")

    return ValidationResult(errors=errors, warnings=warnings)


def build_all(root: Path) -> tuple[list[str], list[str]]:
    skills = build_skill_projection(root)
    agents = build_agent_projections(root)
    return skills, agents


def _default_root() -> Path:
    return Path(__file__).resolve().parent.parent


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build or validate the agent governance framework.")
    parser.add_argument("command", choices=("build", "validate"))
    parser.add_argument("--root", default=str(_default_root()))
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    if args.command == "build":
        skills, agents = build_all(root)
        print(f"built-skills={len(skills)} built-agents={len(agents)}")
        return 0

    result = validate_repository(root)
    for warning in result.warnings:
        print(f"WARNING: {warning}")
    for error in result.errors:
        print(f"ERROR: {error}")
    if result.errors:
        return 1
    print("validation-ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
